// Transactional access only. Never subscribe a buyer or expose acquisition data.
export const ORIGIN = 'https://speedandform.com';
export const EMAIL_VERSION = 'rpd-access-2026-10-04-v1';
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function purchaseAccessEmail({ sessionId, email }) {
  if (!/^cs_[A-Za-z0-9_]+$/.test(sessionId)) throw new Error('Invalid checkout session');
  if (typeof email !== 'string' || !/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(email)) throw new Error('Invalid purchase email');
  const plan = `${ORIGIN}/plans/race-pace-durability/?purchase_session=${encodeURIComponent(sessionId)}`;
  const restore = `${ORIGIN}/plans/race-pace-durability/access/`;
  const subject = 'Your Race Pace That Lasts plan is ready';
  const text = `Your full plan is ready.\n\nYour purchase is complete. All 15 weeks of Race Pace That Lasts are unlocked.\n\nOpen the full plan: ${plan}\n\nChoose your race-pace band, then follow the week. The light and dark print editions are beneath the training.\n\n$79 one-time payment. No subscription. Stripe sends your payment receipt separately.\n\nOn another device, restore access with the email used at checkout: ${restore}\n\nKeep your plan link private. Need help? Reply to this email or contact support@speedandform.com.\n\nFORM · Speed & Form\n`;
  const html = `<!doctype html><html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${subject}</title></head><body style="margin:0;background:#f5f5f7"><table lang="en" dir="ltr" role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td align="center" style="padding:32px 18px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:580px"><tr><td bgcolor="#ffffff" style="padding:40px 28px;background:#ffffff;font-family:Arial,Helvetica,sans-serif;color:#111111"><p style="margin:0 0 36px;font-size:25px;line-height:30px;font-weight:700">FORM.</p><h1 style="margin:0 0 20px;font-size:30px;line-height:36px;font-weight:600">Your full plan is ready.</h1><p style="margin:0 0 26px;font-size:17px;line-height:27px;color:#333333">Your purchase is complete. All 15 weeks of Race Pace That Lasts are unlocked.</p><table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr><td bgcolor="#111111" style="border-radius:3px"><a href="${esc(plan)}" style="display:inline-block;padding:16px 24px;font-size:16px;line-height:24px;font-weight:600;color:#ffffff;text-decoration:none">Open the full plan</a></td></tr></table><p style="margin:26px 0 22px;font-size:16px;line-height:26px;color:#333333">Choose your race-pace band, then follow the week. The light and dark print editions are beneath the training.</p><p style="margin:0 0 22px;font-size:15px;line-height:24px;color:#5b5b60">$79 one-time payment. No subscription.<br>Stripe sends your payment receipt separately.</p><p style="margin:0 0 22px;font-size:15px;line-height:24px;color:#5b5b60">On another device, <a href="${restore}" style="color:#111111">restore access</a> with the email used at checkout.</p><p style="margin:0;font-size:15px;line-height:24px;color:#5b5b60">Keep your plan link private.<br>Need help? Reply to this email or <a href="mailto:support@speedandform.com" style="color:#111111">contact FORM support</a>.</p></td></tr><tr><td style="padding:24px 14px 0;font-family:Arial,Helvetica,sans-serif;font-size:13px;line-height:21px;color:#62626a">FORM · Speed &amp; Form</td></tr></table></td></tr></table></body></html>`;
  return { from:'FORM <hello@send.speedandform.com>', to:[email.trim().toLowerCase()], reply_to:'support@speedandform.com', subject, html, text };
}
