/* No network calls. Records and calculations stay on this device. */
(function () {
'use strict';
const stations=['SkiErg','Sled push','Sled pull','Burpee broad jumps','Row','Farmer’s carry','Sandbag lunges','Wall balls'];
function seconds(s){if(typeof s!=='string'||!s.trim())return null;const p=s.trim().split(':');if(p.length<2||p.length>3||!p.every(x=>/^\d+$/.test(x)))return NaN;if(+p.at(-1)>59||(p.length===3&&+p[1]>59))return NaN;return p.reduce((a,v)=>a*60+Number(v),0);}
function time(n){if(!Number.isFinite(n))return '—';n=Math.round(n);const sign=n<0?'−':'';n=Math.abs(n);return sign+(n>=3600?Math.floor(n/3600)+':'+String(Math.floor(n/60)%60).padStart(2,'0'):Math.floor(n/60))+':'+String(n%60).padStart(2,'0');}
function sum(a){return a.length&&a.every(Number.isFinite)?a.reduce((x,y)=>x+y,0):null;}
function analyze(d){const runs=d.runs.map(r=>seconds(r.time)),work=d.runs.map(r=>seconds(r.station));const distances=d.runs.map(r=>r.km.trim()?Number(r.km):null);const run=sum(runs),station=sum(work);const km=distances.every(x=>Number.isFinite(x)&&x>0)?sum(distances):null;const pace=run!==null&&km?run/km:null;const early=km&&run!==null?sum(runs.slice(0,3))/sum(distances.slice(0,3)):null,late=km&&run!==null?sum(runs.slice(5,8))/sum(distances.slice(5,8)):null;const threshold=seconds(d.threshold);return {runs,work,run,station,pace,early,late,retention:pace&&threshold>0?threshold/pace*100:null,total:sum([run,station,seconds(d.rox),seconds(d.penalty)])};}
if(typeof module!=='undefined'&&module.exports){module.exports={seconds,time,analyze};return;}
const $=id=>document.getElementById(id),key='form-hyrox-workbench-v1';
const fields=['athlete','event','date','division','source','confidence','overall','rox','penalty','conditions','threshold','tenK','oneK','benchmarkDate','benchmarkMethod','target','as','ar','al','bs','br','bl','observed','hypothesis','test','decision'];
const times=['overall','rox','penalty','threshold','tenK','oneK','target','as','ar','al','bs','br','bl'];
let records=[],active='',dirty=false,storageBlocked=false;
function cell(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;}
for(let i=0;i<8;i++){const row=cell('tr');row.append(cell('td',`${i+1}. Run → ${stations[i]}`));for(const [kind,label] of [['time','Run duration'],['km','Measured run distance in km'],['station','Station duration'],['note','Observation']]){const td=cell('td'),input=cell('input');input.id=`${kind}${i}`;input.setAttribute('aria-label',`${label}, pair ${i+1}`);input.placeholder=kind==='km'?'Unknown':kind==='note'?'Optional':'m:ss';input.maxLength=kind==='note'?600:20;td.dataset.label=label;td.append(input);row.append(td);} $('splits').append(row);}
function snapshot(){const d={version:1,id:active||crypto.randomUUID(),runs:[]};fields.forEach(f=>d[f]=$(f).value);for(let i=0;i<8;i++)d.runs.push({time:$('time'+i).value,km:$('km'+i).value,station:$('station'+i).value,note:$('note'+i).value});return d;}
function valid(d){return d&&d.version===1&&typeof d.id==='string'&&fields.every(f=>typeof d[f]==='string'&&d[f].length<20000)&&Array.isArray(d.runs)&&d.runs.length===8&&d.runs.every(r=>r&&['time','km','station','note'].every(f=>typeof r[f]==='string'&&r[f].length<20000));}
function load(d){fields.forEach(f=>$(f).value=d?d[f]:'');if(!d){$('division').selectedIndex=0;$('confidence').selectedIndex=0;}for(let i=0;i<8;i++)for(const k of ['time','km','station','note'])$(k+i).value=d?d.runs[i][k]:'';active=d?d.id:'';dirty=false;draw();$('saveStatus').textContent=d?'Loaded record':'Unsaved record';}
function refreshList(){const list=$('records');list.replaceChildren(new Option('New record',''));records.forEach(d=>list.add(new Option([d.athlete||'Unnamed',d.event||'Session',d.date].filter(Boolean).join(' · '),d.id)));list.value=active;}
function metric(label,value){const e=cell('div');e.className='metric';e.append(cell('strong',value),cell('span',label));$('metrics').append(e);}
function draw(){const d=snapshot(),a=analyze(d);let errors=0;for(const id of [...times,...Array.from({length:8},(_,i)=>['time'+i,'station'+i]).flat()]){const e=$(id),n=seconds(e.value),bad=Number.isNaN(n)||(n===0&&!['penalty','al','bl'].includes(id));e.setAttribute('aria-invalid',String(bad));if(bad)errors++;}for(let i=0;i<8;i++){const e=$('km'+i),bad=!!e.value.trim()&&(!Number.isFinite(Number(e.value))||Number(e.value)<=0);e.setAttribute('aria-invalid',String(bad));if(bad)errors++;}
$('metrics').replaceChildren();metric('Run total · entered splits',time(a.run));metric('Station total · entered splits',time(a.station));metric('Roxzone · entered',time(seconds(d.rox)));metric('Overall · reported',time(seconds(d.overall)));
const overall=seconds(d.overall);$('reconcile').textContent=errors?'Correct the highlighted durations or distances. Use m:ss or h:mm:ss; unknown stays blank.':a.total===null?'Enter all splits, Roxzone and non-overlapping penalties to reconcile the total. Blank does not mean zero.':overall===null?'Entered components total '+time(a.total)+'. Add the reported overall time to compare.':a.total===overall?'Entered components match the reported overall time.':`Entered components total ${time(a.total)}; difference from reported finish: ${time(a.total-overall)}. Verify timing boundaries, rounding and penalty allocation before interpreting.`;
$('chart').replaceChildren();const max=Math.max(1,...a.runs.filter(Number.isFinite));a.runs.forEach((v,i)=>{const e=cell('div');e.className='barrow';const b=cell('div');b.className='bar';b.style.width=Number.isFinite(v)?(v/max*100)+'%':'0';e.append(cell('span','Run '+(i+1)),b,cell('span',time(v)));$('chart').append(e);});
$('benchRead').replaceChildren();const add=t=>$('benchRead').append(cell('p',t));if(a.pace){add(`Distance-normalized running: ${time(a.pace)}/km · ${time(a.pace*1.609344)}/mi.`);if(a.retention!==null)add(`Threshold gap: ${time(a.pace-seconds(d.threshold))}/km. Velocity retention: ${a.retention.toFixed(1)}%. Descriptive only.`);}else add('Add measured distances for all eight runs to calculate normalized pace and threshold retention.');if(seconds(d.tenK)>0)add(`10K reference: ${time(seconds(d.tenK)/10)}/km.`);if(seconds(d.oneK)>0)add(`Fresh 1K reference: ${time(seconds(d.oneK))}.`);
const maxStation=Math.max(...a.work.filter(Number.isFinite));$('priority').textContent=Number.isFinite(maxStation)?`Largest entered station: ${stations[a.work.indexOf(maxStation)]} · ${time(maxStation)}. Start by asking how that time was spent; largest duration is not automatically the largest recoverable opportunity.`:'Enter the record, then choose a question worth testing.';
$('lateRead').textContent=a.pace&&Number.isFinite(a.early)&&Number.isFinite(a.late)?`Runs 1–3: ${time(a.early)}/km. Runs 6–8: ${time(a.late)}/km. Change: ${time(a.late-a.early)}/km. Check timing boundaries before interpreting.`:'Early/late pace comparison appears once all run times and measured distances are entered.';
$('pairs').replaceChildren();a.work.forEach((v,i)=>{const r=cell('tr'),km=i<7?Number(d.runs[i+1].km):0,target=seconds(d.target),next=i<7?a.runs[i+1]:null;const gap=i<7&&km>0&&Number.isFinite(next)&&target>0?time(next/km-target)+'/km':'—';[stations[i],time(v),i<7?`Run ${i+2} · ${time(next)}`:'Finish — no next run',i<7?time(sum([v,next])):'—',gap].forEach(t=>r.append(cell('td',t)));$('pairs').append(r);});
const av=sum([seconds(d.as),seconds(d.ar)]),bv=sum([seconds(d.bs),seconds(d.br)]);let tr='Enter both station–run trials to compare their combined time.';if(av!==null&&bv!==null){const delta=av-bv;tr=`A: ${time(av)}. B: ${time(bv)}. ${delta===0?'The pairs are equal.':(delta>0?'B':'A')+' saves '+time(Math.abs(delta))+' across the pair.'}`;const al=seconds(d.al),bl=seconds(d.bl);tr+=al!==null&&bl!==null?` Including entered later costs: A ${time(av+al)}, B ${time(bv+bl)}.`:' Later costs are unknown; this is not a full-race prediction.';}$('trade').textContent=tr;
return errors===0;}
$('save').onclick=()=>{if(!draw()){$('saveStatus').textContent='Correct highlighted fields before saving.';return;}if(storageBlocked){$('saveStatus').textContent='Existing storage could not be read. Export this record instead.';return;}const d=snapshot(),next=records.filter(r=>r.id!==d.id).concat(d);try{localStorage.setItem(key,JSON.stringify(next));records=next;active=d.id;dirty=false;refreshList();$('saveStatus').textContent='Saved on this browser';}catch(_){$('saveStatus').textContent='Browser storage unavailable. Export to keep this record.';}};
$('records').onchange=()=>{const id=$('records').value;if(dirty&&!confirm('Discard unsaved edits and open another record?')){$('records').value=active;return;}load(records.find(r=>r.id===id));};
$('new').onclick=()=>{if(dirty&&!confirm('Discard unsaved edits and start a new record?'))return;load();refreshList();};
$('export').onclick=()=>{if(!draw()){$('saveStatus').textContent='Correct highlighted fields before exporting.';return;}const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}));a.href=url;a.download='form-hyrox-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;try{if(f.size>500000)throw Error('File too large');const d=JSON.parse(await f.text());if(!valid(d))throw Error('Not a supported record');if(dirty&&!confirm('Discard unsaved edits and open imported record?'))return;d.id=crypto.randomUUID();load(d);refreshList();dirty=true;$('saveStatus').textContent='Imported as a new record. Review, then save.';}catch(e){$('saveStatus').textContent='Import failed: '+e.message;}finally{$('file').value='';}};
let printDetails=[];window.addEventListener('beforeprint',()=>{printDetails=[...document.querySelectorAll('main details')].map(e=>[e,e.open]);printDetails.forEach(([e])=>e.open=true);document.querySelectorAll('textarea').forEach(e=>{e.dataset.printHeight=e.style.height;e.style.height=e.scrollHeight+'px';});});window.addEventListener('afterprint',()=>{printDetails.forEach(([e,open])=>e.open=open);document.querySelectorAll('textarea').forEach(e=>e.style.height=e.dataset.printHeight||'');});document.querySelectorAll('.mobile-menu a').forEach(a=>a.addEventListener('click',()=>a.closest('details').open=false));$('print').onclick=()=>window.print();document.querySelectorAll('main input:not([type=file]),main textarea,main select:not(#records)').forEach(e=>e.addEventListener('input',()=>{if(e.id.startsWith('budget-')||e.id.startsWith('plan-'))return;dirty=true;draw();$('saveStatus').textContent='Unsaved changes';}));window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
try{const raw=localStorage.getItem(key);if(raw){const parsed=JSON.parse(raw);if(!Array.isArray(parsed)||!parsed.every(valid))throw Error();records=parsed;}}catch(_){storageBlocked=true;}
refreshList();load();if(storageBlocked)$('saveStatus').textContent='Saved records could not be read. Export new work; existing bytes were preserved.';
})();
