const assert=require('node:assert/strict');
const {seconds,time,analyze}=require('./workbench.js');
assert.equal(seconds('1:22:16'),4936);
assert.ok(Number.isNaN(seconds('4:99')));
assert.equal(seconds(''),null);
assert.equal(time(null),'—');
const d={runs:Array.from({length:8},()=>({time:'4:00',station:'3:00',km:''})),threshold:'3:50',rox:'5:00',penalty:'0:00'};
assert.equal(analyze(d).total,3660);
assert.equal(analyze(d).retention,null);
d.runs.forEach(r=>r.km='1');
assert.equal(analyze(d).pace,240);
assert.equal(analyze(d).retention,230/240*100);
d.penalty='';assert.equal(analyze(d).total,null);
d.runs[0].time='';assert.equal(analyze(d).run,null);
console.log('PASS: parsing, unknowns, totals, measured distance and retention');

const z={runs:Array.from({length:8},(_,i)=>({time:i<3?'4:00':'5:00',station:'3:00',km:i<3?'1':'1.25'})),threshold:'3:50',rox:'5:00',penalty:'0:00'};
assert.equal(analyze(z).early,240);assert.equal(analyze(z).late,240);
z.runs[0].time='';assert.equal(analyze(z).early,null);
console.log('PASS: distance-adjusted early/late comparison and missing-run guard');
const {pairRows}=require('./workbench.js');
const example={runs:Array.from({length:8},(_,i)=>({time:'4:00',station:'2:00',km:'1',note:''}))};
const rows=pairRows(example);
assert.equal(rows[0].total,360);
assert.equal(rows[6].run,240);
assert.equal(rows[7].total,120);
assert.equal(rows[7].run,null);
assert.equal(rows.reduce((a,r)=>a+r.total,0)+240,8*360);
example.runs[1].time='';assert.equal(pairRows(example)[0].total,null);assert.equal(pairRows(example)[0].station,120);
example.runs[1].time='0:00';assert.equal(pairRows(example)[0].complete,false);
example.runs[1].time='bad';assert.equal(pairRows(example)[0].run,null);
console.log('PASS record-derived pairs, missing inputs and finish without double counting');
