/* Clock guidance, local timers and message drafts. No completed-work writes. */
(function(){'use strict';var root=document.getElementById('your-day');if(!root)return;var tabs=Array.from(root.querySelectorAll('[role=tab]')),config={coachSmsRecipient:null,athletePhotos:{}};
function pick(tab,focus){tabs.forEach(function(t){var on=t===tab;t.setAttribute('aria-selected',String(on));t.tabIndex=on?0:-1;document.getElementById(t.getAttribute('aria-controls')).hidden=!on;});if(focus)tab.focus();markNext();}
tabs.forEach(function(t,i){t.addEventListener('click',function(){pick(t,false);});t.addEventListener('keydown',function(e){var n;if(e.key==='ArrowRight')n=(i+1)%tabs.length;else if(e.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=tabs.length-1;else return;e.preventDefault();pick(tabs[n],true);});});
function markNext(){var d=new Date(),mins=d.getHours()*60+d.getMinutes(),kind=d.getDay()===6?'day-sat':d.getDay()===0?'day-sun':'day-work';root.querySelectorAll('.next-tag').forEach(function(e){e.remove();});root.querySelectorAll('.receded').forEach(function(e){e.classList.remove('receded');});var panel=document.getElementById(kind);if(panel.hidden)return;var rows=Array.from(panel.querySelectorAll('li[data-at]')),next=rows.find(function(e){return Number(e.dataset.at)>=mins;});rows.forEach(function(e){if(Number(e.dataset.at)<mins)e.classList.add('receded');});if(next){var tag=document.createElement('span');tag.className='next-tag';tag.textContent='Next';tag.title='Next scheduled time, not a meal record';next.querySelector('.what').prepend(tag);}}
var today=new Date().getDay();pick(tabs[today===6?1:today===0?2:0],false);setInterval(markNext,30000);document.addEventListener('visibilitychange',function(){if(!document.hidden)markNext();});
function revealHash(){var id;try{id=decodeURIComponent(location.hash.slice(1));}catch(e){return;}if(id==='weekends'){pick(tabs[new Date().getDay()===0?2:1],false);root.scrollIntoView();return;}var el=document.getElementById(id);if(!el)return;var panel=el.closest('.rail-day');if(panel)pick(tabs.find(function(t){return t.getAttribute('aria-controls')===panel.id;}),false);var p=el;while(p){if(p.tagName==='DETAILS')p.open=true;p=p.parentElement;}if(el.matches('.recipe-card'))el.querySelector('details').open=true;requestAnimationFrame(function(){el.scrollIntoView({block:'start'});});}window.addEventListener('hashchange',revealHash);revealHash();
var timers=new Map();function updateTimers(){var now=Date.now();timers.forEach(function(end,b){var sec=Math.max(0,Math.ceil((end-now)/1000));if(!sec){timers.delete(b);b.textContent='Done · '+b.dataset.label;b.setAttribute('aria-pressed','false');document.getElementById('cook-timer-note').textContent=b.dataset.label+' timer finished. Check the cooking cue.';}else b.textContent=Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0')+' · Stop';});}document.querySelectorAll('.cook-timer').forEach(function(b){b.setAttribute('aria-pressed','false');b.addEventListener('click',function(){if(timers.has(b)){timers.delete(b);b.textContent='Start '+b.dataset.label;b.setAttribute('aria-pressed','false');}else{timers.set(b,Date.now()+Number(b.dataset.seconds)*1000);b.setAttribute('aria-pressed','true');updateTimers();}});});setInterval(updateTimers,1000);document.addEventListener('visibilitychange',updateTimers);
function noteText(type){if(type==='start')return 'Started today, '+new Date().toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'})+'.';return 'Day-7 note\nBreakfasts eaten: \n3:30 meals eaten: \nBed and wake times: \nHunger between meals: \nAppetite at dinner: \nDigestion: \nSoreness: \nRuns felt: ';}
function smsLink(body){var phone=config.coachSmsRecipient;phone=typeof phone==='string'&&/^\+[1-9]\d{6,14}$/.test(phone)?phone:'';var apple=/iPhone|iPad|iPod/.test(navigator.userAgent)||(/Macintosh/.test(navigator.userAgent)&&navigator.maxTouchPoints>1);return 'sms:'+phone+(apple?'&':'?')+'body='+encodeURIComponent(body);}
document.querySelectorAll('[data-note]').forEach(function(b){b.addEventListener('click',function(){var draft=document.getElementById('text-draft'),area=document.getElementById('note-copy');area.value=noteText(b.dataset.note);document.getElementById('note-sms').href=smsLink(area.value);draft.hidden=false;document.getElementById('note-help').textContent=config.coachSmsRecipient?'Review your draft before sending.':'Choose Brice as recipient. Copy the text if Messages does not fill it.';draft.scrollIntoView({block:'nearest'});area.focus();});});
document.getElementById('note-copy-button').addEventListener('click',async function(){var area=document.getElementById('note-copy'),help=document.getElementById('note-help');try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(area.value);help.textContent='Copied. Paste into your conversation with Brice.';}else{area.select();help.textContent=document.execCommand('copy')?'Copied. Paste into Messages.':'Select and copy the draft, then paste into Messages.';}}catch(e){area.select();help.textContent='Select and copy the draft, then paste into Messages.';}});
function applyPhoto(id,photo){if(!photo||typeof photo.src!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(photo.date)||!photo.src.startsWith('./athlete-photos/'))return;var card=document.getElementById(id);if(!card)return;var url=new URL(photo.src,location.href);if(url.origin!==location.origin)return;var probe=new Image();probe.onload=function(){card.querySelector('img').src=url.href;card.querySelector('img').alt='Your batch, '+photo.date;card.querySelector('figcaption').textContent='Your batch, '+photo.date;};probe.src=url.href;}
fetch('./page-config.json',{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('config');return r.json();}).then(function(c){config=c;Object.keys(c.athletePhotos||{}).forEach(function(id){applyPhoto(id,c.athletePhotos[id]);});}).catch(function(){});
var state;window.addEventListener('beforeprint',function(){state={details:Array.from(document.querySelectorAll('details')).map(function(d){return [d,d.open];}),panels:Array.from(root.querySelectorAll('.rail-day')).map(function(d){return [d,d.hidden];})};state.details.forEach(function(d){d[0].open=true;});state.panels.forEach(function(d){d[0].hidden=false;});});window.addEventListener('afterprint',function(){if(!state)return;state.details.forEach(function(d){d[0].open=d[1];});state.panels.forEach(function(d){d[0].hidden=d[1];});});})();
