'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const html = fs.readFileSync('index.html', 'utf8');
assert.equal((html.match(/<h1>Run<br>Development<\/h1>/g) || []).length, 1);
assert.equal((html.match(/class="hero-benefit">Run better.<\/strong>/g) || []).length, 1);
assert.equal((html.match(/<strong>8 weeks · \$1,200<\/strong>/g) || []).length, 1);
assert.doesNotMatch(html, /hero-kicker/);
assert.doesNotMatch(html, /hero-reassurance/);
assert.doesNotMatch(html, /first Miami track assessment is complimentary/i);
assert.doesNotMatch(html, /id="inquiry-reassurance"/);
assert.doesNotMatch(html, /An inquiry only\. No payment or booking yet\./);
assert.doesNotMatch(html, /I read every inquiry myself\./);
assert.doesNotMatch(html, /Coaching you’re interested in/);
assert.doesNotMatch(html, /Run better\. Get faster\. Run farther\./);
assert.match(html, /<meta property="og:title" content="Run better\. \| FORM">/);
assert.match(html, /<label class="coaching-select-label sr-only" for="coachingChoice">Coaching<\/label>/);
assert.match(html, /<h1>Run<br>Development<\/h1>/);
assert.match(html, /class="hero-benefit">Run better\.<\/strong>/);
assert.match(html, /<div class="offer"><strong>8 weeks · \$1,200<\/strong><\/div>/);
assert.match(html, /<dt>Plan<\/dt><dd>Your week\.<\/dd>/);
assert.match(html, /<dt>Practice<\/dt><dd>Weekly track\.<\/dd>/);
assert.match(html, /<dt>Adjust<\/dt><dd>As you develop\.<\/dd>/);
assert.match(html, /assets\/home\/practice\/coaching-track\.webp/);
assert.doesNotMatch(html, /id="analysisVideo"/);
assert.match(html, /data-coaching="remote">Discuss remote coaching/);
assert.doesNotMatch(html, /We change what matters, practice it/);
assert.doesNotMatch(html, /Running coaching with Brice\.<br>Miami \+ Remote/);
assert.doesNotMatch(html, /id="simon"/);
assert.match(html, /<h2>I develop<br>runners\.<\/h2>/);
assert.match(html, /I look for ease\./);
assert.match(html, /Running should click\./);
assert.match(html, /Not five things at once\./);
assert.match(html, /Ten minutes counts\./);
assert.match(html, /Reveal what wants to be set free\./);
assert.match(html, /<p class="training-caption">One session belongs to a week\.<\/p>/);
assert.match(html, /<h2>Tell me about<br>your running\.<\/h2>/);
assert.doesNotMatch(html, /Your next step<br>starts here/);
assert.doesNotMatch(html, /footer-location/);
console.log('PASS: manifesto-first homepage, doctrine-aligned share copy, sparse hero, concise offer, static track proof, simplified inquiry, and footer.');
