'use strict';
const protectedBaseline=require('../scripts/protected-site-baseline.cjs');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),cp=require('node:child_process');
const s=require('../scripts/share-metadata.cjs'),state=require('../scripts/sculpt-landing-state.cjs');
const ROOT=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(ROOT,f),'utf8'),old=f=>cp.execFileSync('git',['show',protectedBaseline(f,state.manifest.baseCommit)+':'+f],{cwd:ROOT,maxBuffer:30_000_000});
const h=read('forge-sculpt/index.html'),ids=t=>[...t.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
state.verify('forge-sculpt/index.html',h);assert.equal(s.sha(old('forge-sculpt/index.html')),state.manifest.pages[0].beforeSha256);
const form=read('form/index.html');assert.equal(form,old('form/index.html').toString().replace('>RUNNER<span>','>JOSÉ<span>'),'Only the requested FORM identity changes');
assert.equal(s.sha(form),state.manifest.formIdentity.afterSha256);assert.ok(h.includes('>ADRIAN<span>')&&h.includes('App illustration · sample training'));
let kept=0;for(const f of cp.execFileSync('git',['ls-tree','-r','--name-only',state.manifest.baseCommit],{cwd:ROOT,encoding:'utf8'}).trim().split('\n').filter(f=>f.endsWith('.html')&&!['form/index.html','forge-sculpt/index.html'].includes(f))){assert.equal(s.sha(read(f)),s.sha(old(f)),f+' outside Pass 5B');kept++;}
for(const f of ['css/cream-reading.css','css/homepage.css','css/form-landing.css','js/form-landing.js','js/homepage-motion.js','js/coaching-measurement.js','css/track-gallery.css','js/track-gallery.js','track/albums.json','track/media-manifest.json','netlify.toml','_headers','_redirects','robots.txt','sitemap.xml','search-index.json','scripts/discovery-catalog.cjs','plans/race-pace-durability/source.js','forge-sculpt/train/data/forge-portal-programs.json'])assert.equal(s.sha(read(f)),s.sha(old(f)),f+' protected');
assert.equal((h.match(/<h1\b/g)||[]).length,1);assert.equal((h.match(/<main\b/g)||[]).length,1);assert.equal(ids(h).length,new Set(ids(h)).size);for(const id of state.manifest.retainedFragments)assert.ok(ids(h).includes(id),'Kept public fragment #'+id);
assert.equal(s.canonical(h),'https://speedandform.com/forge-sculpt/');assert.equal(s.meta(h,'og:title'),s.meta(h,'twitter:title'));assert.equal(s.meta(h,'description'),s.meta(h,'og:description'));assert.equal(s.meta(h,'og:image'),s.ORIGIN+'/assets/forge/og-sculpt-20260917.jpg');assert.equal(s.meta(h,'og:image:width'),'1200');assert.equal(s.meta(h,'og:image:height'),'630');
const im=s.imageInfo(ROOT,s.meta(h,'og:image'));assert.equal(im.width,1200);assert.equal(im.height,630);
for(const a of state.manifest.assets)assert.equal(s.sha(fs.readFileSync(path.join(ROOT,a.file))),a.sha256,'Reviewed asset '+a.file);
const schema=JSON.parse(h.match(/id="sculpt-product-schema" type="application\/ld\+json">([\s\S]*?)<\/script>/)[1]);const app=schema['@graph'].find(x=>x['@type']==='SoftwareApplication');assert.equal(app.name,'Breechay');assert.ok(app.downloadUrl.endsWith('/id6790569283'));assert.ok(!app.aggregateRating&&!app.review&&!app.offers,'No fabricated reviews or unqualified billing markup');
for(const m of h.matchAll(/href="([^"]+)"/g)){const u=new URL(s.attrs(m[0]).href,s.ORIGIN+'/forge-sculpt/');if(u.origin!==s.ORIGIN){assert.equal(u.href,app.downloadUrl);continue;}const r=u.pathname.slice(1),f=[r||'index.html',r+'.html',r.replace(/\/$/,'')+'/index.html'].find(f=>fs.existsSync(path.join(ROOT,f))&&fs.statSync(path.join(ROOT,f)).isFile());assert.ok(f,'Local target '+u);if(u.hash)assert.ok(ids(read(f)).includes(decodeURIComponent(u.hash.slice(1))),'Local fragment '+u);}
assert.ok(h.includes('$199.99')&&h.includes('Auto-renews annually')&&h.includes('at least 24 hours before renewal'));
assert.ok(!/Notify me|Get notified at launch|by Sunday|four-phase|267 sessions|49 training weeks|you cannot browse|If you could build it yourself|data-netlify|<form[ >]|fonts\.googleapis|—/.test(h),'Retired claims, launch form, faint external fonts and em dashes removed');
const js=read('js/sculpt-landing.js');assert.ok(!/innerHTML|fetch\(|localStorage|sessionStorage|XMLHttpRequest|sendBeacon|eval\(/.test(js),'Sample never stores or transmits a record');
const {validate}=require('../js/sculpt-landing.js');assert.deepEqual(validate('25','15'),{weight:25,reps:15});assert.deepEqual(validate('12.5','1'),{weight:12.5,reps:1});assert.deepEqual(validate('0','100'),{weight:0,reps:100});
for(const x of ['',null,undefined,NaN,Infinity,true,-1,501,.25,'<script>'])assert.equal(validate(x,15).field,'weight');
for(const x of ['',null,undefined,NaN,Infinity,true,0,101,1.5,'<script>'])assert.equal(validate(25,x).field,'reps');
const css=read('css/sculpt-landing.css');assert.ok(css.includes('prefers-reduced-motion')&&css.includes('@container sculpt-page'));assert.ok(!/overflow(?:-x)?\s*:\s*hidden/.test(css),'Do not conceal reflow defects');
function lum(c){const x=c.match(/../g).map(n=>parseInt(n,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return x[0]*.2126+x[1]*.7152+x[2]*.0722;}
for(const [a,b] of [['f0ece3','090908'],['b7b1a5','090908'],['c9b285','090908'],['24221d','efebe2'],['5f584c','efebe2'],['685430','efebe2']])assert.ok((Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05)>=4.5,'Readable palette '+a+'/'+b);
console.log('PASS: Sculpt landing; José-only FORM change; '+kept+' other HTML files and critical sources unchanged; verified media, twelve phases, app destination, billing language, fragments, contrast and ephemeral demo validation.');
