// One operational message. Never substitutes for a campaign or a consent decision.
export const ORIGIN = 'https://speedandform.com';
export const CONSENT = 'FORM email updates: Field Notes, track photographs and run announcements.';
export const CONSENT_VERSION = '2026-09-17-v1';
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function confirmationEmail({ email, token, optout, postalAddress, requestId, endpoint }) {
  if (!postalAddress || postalAddress.length < 12) throw Error('A public business mailing address is required');
  if (![token, optout].every(v => /^[A-Za-z0-9_-]{43}$/.test(v))) throw Error('Invalid token');
  const confirm = `${ORIGIN}/updates/#confirm=${token}`;
  const stop = `${ORIGIN}/updates/#unsubscribe=${optout}`;
  const oneClick = `${endpoint}/unsubscribe?token=${optout}`;
  const title = 'Confirm your FORM updates';
  const text = `Confirm your FORM updates\n\nYou asked for occasional Field Notes, track photographs and run announcements from Brice.\n\nConfirm your email: ${confirm}\n\nThis link is valid for 24 hours. You are not subscribed until you confirm. If you did not request this, ignore this email or cancel the request: ${stop}\n\nQuestions? Reply to brice@speedandform.com.\n\nSpeed & Form / Vinchay Labs LLC\n${postalAddress}\n`;
  // Inline, table-based layout also provides a plain-text equivalent above.
  const html = `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>${title}</title></head><body style="margin:0;background-color:#f5f5f7"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td align="center" style="padding-top:32px;padding-right:18px;padding-bottom:32px;padding-left:18px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:580px"><tr><td bgcolor="#ffffff" style="background-color:#ffffff;padding-top:40px;padding-right:32px;padding-bottom:40px;padding-left:32px"><p style="margin-top:0;margin-bottom:36px;font-family:Arial,Helvetica,sans-serif;font-size:25px;line-height:30px;color:#111111;font-weight:700">FORM<span style="color:#729714">.</span></p><h1 style="margin-top:0;margin-bottom:22px;font-family:Arial,Helvetica,sans-serif;font-size:30px;line-height:36px;color:#111111;font-weight:600">Confirm your email.</h1><p style="margin-top:0;margin-bottom:26px;font-family:Arial,Helvetica,sans-serif;font-size:17px;line-height:27px;color:#333333">You asked for occasional Field Notes, track photographs and run announcements from Brice.</p><table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr><td bgcolor="#111111" style="background-color:#111111;border-radius:4px"><a href="${esc(confirm)}" style="display:inline-block;padding-top:16px;padding-right:24px;padding-bottom:16px;padding-left:24px;font-family:Arial,Helvetica,sans-serif;font-size:16px;line-height:24px;color:#ffffff;text-decoration:none;font-weight:600">Confirm my email</a></td></tr></table><p style="margin-top:26px;margin-bottom:20px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:24px;color:#5b5b60">This link is valid for 24 hours. You are not subscribed until you confirm.</p><p style="margin-top:0;margin-bottom:28px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:24px;color:#5b5b60">Did not request this? Ignore this email or <a href="${esc(stop)}" style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:24px;color:#111111">cancel the request</a>.</p><p style="margin-top:0;margin-bottom:0;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:24px;color:#5b5b60">Questions? Reply to this email.<br>Brice · FORM</p></td></tr><tr><td style="padding-top:24px;padding-right:16px;padding-bottom:0;padding-left:16px"><p style="margin-top:0;margin-bottom:0;font-family:Arial,Helvetica,sans-serif;font-size:12px;line-height:20px;color:#62626a">Speed &amp; Form / Vinchay Labs LLC<br>${esc(postalAddress).replaceAll('\n','<br>')}</p></td></tr></table></td></tr></table></body></html>`;
  return {from:'FORM <updates@send.speedandform.com>',to:[email],reply_to:'brice@speedandform.com',subject:title,html,text,
    headers:{'List-Unsubscribe':`<${oneClick}>`,'List-Unsubscribe-Post':'List-Unsubscribe=One-Click'},
    tags:[{name:'stream',value:'form_updates'},{name:'request_id',value:requestId}]};
}
