'use strict';
// Disposable local acceptance server. NEVER deployed as an Edge Function.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {rpc,pool,env,provider,initialize,reset}=require('./helpers.cjs');
(async()=>{await initialize();const fake=provider();const {createHandler}=await import('../../supabase/functions/email-updates/core.mjs');const handler=createHandler({env,rpc,fetch:fake.fetch});const root=path.resolve(__dirname,'../..');
const server=http.createServer(async(req,res)=>{try{const origin='http://127.0.0.1:'+server.address().port,u=new URL(req.url,origin);if(u.pathname==='/__fixture/reset'&&req.method==='POST'){await reset();fake.requests.length=0;res.end('{}');return;}
if(u.pathname==='/__fixture/mail'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(fake.requests));return;}
if(u.pathname.startsWith('/api/')){const chunks=[];for await(const chunk of req)chunks.push(chunk);const request=new Request(env.SUPABASE_URL+'/functions/v1/email-updates/'+u.pathname.slice(5)+u.search,{method:req.method,headers:{...req.headers,origin:'https://speedandform.com'},body:['GET','HEAD'].includes(req.method)?undefined:Buffer.concat(chunks)});const result=await handler(request);res.writeHead(result.status,Object.fromEntries(result.headers));res.end(Buffer.from(await result.arrayBuffer()));return;}
let f=path.resolve(root,'.'+u.pathname);if(!f.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404);res.end('Missing');return;}let body=fs.readFileSync(f);const ext=path.extname(f);const mime={'.html':'text/html','.css':'text/css','.js':'application/javascript','.json':'application/json','.jpg':'image/jpeg','.ico':'image/x-icon'};if(ext==='.html')body=Buffer.from(body.toString().replace('https://pbgsjjegycacodiltbhn.supabase.co/functions/v1/email-updates',origin+'/api'));res.setHeader('Content-Type',mime[ext]||'application/octet-stream');res.end(body);
}catch{res.writeHead(500);res.end('Fixture error');}});server.listen(4179,'127.0.0.1',()=>console.log('Newsletter fixture ready'));process.on('SIGTERM',()=>server.close(()=>pool.end()));})();
