import { supabase } from '/private/supabase-client.js';
import { sendMagicLink, signInWithPassword } from '/private/auth.js';
import { AREAS, escapeHtml as e, safeUrl, sourceState, dateLabel, validateBoard, upcomingAppointments } from './model.mjs?v=1';
const $ = s => document.querySelector(s);
let board=null,user=null,tab='today',area='all',loading=false,authGeneration=0;
const closed=i=>['done','cancelled'].includes(i.status);
const statusName=s=>({queued:'Ready',active:'In progress',waiting:'Waiting',done:'Done',cancelled:'Parked'}[s]||s);
const sourceName=s=>({live:'Live records',snapshot:'Checked snapshot',stale:'Check again',conflict:'Needs reconciliation',unavailable:'Unavailable',pending:'Pending',unchecked:'Not checked'}[s]||s);
const checked=v=>v ? new Date(v).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}) : 'Not checked';
function message(text,error=false){ $('#message').textContent=text;$('#message').classList.toggle('error',error); }
function refs(item){ return (item.source_refs||[]).map(r=>{ const u=r.url&&safeUrl(r.url);return u?`<a class="ref" href="${e(u)}" target="_blank" rel="noopener">${e(r.label||'Owning source')} ↗</a>`:`<span class="source-note">${e(r.label||r.record_id||'Source recorded')}</span>`; }).join(' '); }
function meta(item){return `<div class="metadata"><span>${e(AREAS[item.area]||item.area)}</span><span class="pill ${item.status==='waiting'?'warning':''}">${e(statusName(item.status))}</span>${item.due_on?`<span>Due ${e(dateLabel(item.due_on))}</span>`:''}${item.actor!=='brice'?`<span>${item.actor==='agent'?'Agent queue':'Other owner'}</span>`:''}</div>`;}
function actions(item){ if(item.kind!=='task')return '';return `<div class="actions">${!closed(item)?`<button type="button" class="done" data-action="done" data-id="${e(item.id)}">Done</button>${item.status!=='waiting'&&item.actor==='brice'&&item.focus_on!==board?.today?`<button type="button" data-action="focus" data-id="${e(item.id)}">Today</button>`:''}`:''}<button type="button" data-action="edit" data-id="${e(item.id)}">Edit</button></div>`;}
function itemMarkup(item){ const stale=item.expires_at&&Date.parse(item.expires_at)<=Date.now();return `<article class="item">${meta(item)}<h3 style="margin-top:10px">${e(item.title)}</h3>${item.body?`<p>${e(item.body)}</p>`:''}${item.next_action?`<p class="owner-note">${e(item.next_action)}</p>`:''}${item.waiting_on&&item.status==='waiting'?`<p class="small">Waiting on ${e(item.waiting_on)}${item.review_on?` · Review ${e(dateLabel(item.review_on))}`:''}</p>`:''}${item.observed_at?`<p class="small">${stale?'Older snapshot. Recheck before acting. ':''}Source checked ${e(checked(item.observed_at))}.</p>`:''}${refs(item)}${actions(item)}</article>`;}
function athleteName(id){return board.athletes.find(a=>a.id===id)?.first_name||'Athlete';}
function appointmentMarkup(a){let when='Time pending';if(a.time_local){const [h,m]=a.time_local.split(':').map(Number);when=`${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`;}return `<div class="appointment"><time>${e(dateLabel(a.scheduled_on,{weekday:'short',month:'short',day:'numeric'}))} · ${e(when)}</time><b>${e(a.title)}</b>${a.note?`<p class="small">${e(a.note)}</p>`:''}<p class="small">${a.source==='google'?'Calendar projection':'Coach agreement'}${a.status==='tentative'?' · Exact time not booked':''}</p></div>`;}
function coachTask(t){return `<article class="item"><div class="metadata"><span>${e(athleteName(t.athlete_id))}</span><span class="pill warning">${e(t.state.replaceAll('_',' '))}</span>${t.due_on?`<span>Review ${e(dateLabel(t.due_on))}</span>`:''}</div><h3 style="margin-top:10px">${e(t.title)}</h3><p>${e(t.summary)}</p>${t.waiting_on?`<p class="small">Waiting on ${e(t.waiting_on)}</p>`:''}<a class="ref" href="/coach/labs/">Open the coaching record ↗</a></article>`;}
function todayView(){
  const priorities=board.priorities;
  const calendar=board.sources.find(s=>s.source_key==='calendar');
  const upcoming=upcomingAppointments(board.appointments,board.today,board.read_at);
  const personal=board.items.filter(i=>i.kind==='context'&&i.area==='training'&&!closed(i));
  const agents=board.items.filter(i=>i.kind==='task'&&i.actor==='agent'&&!closed(i));
  return `<div class="layout"><div><div class="section-head"><h2>The moves that matter</h2><span class="small">At most four</span></div><div>${priorities.length?priorities.map((i,n)=>`<article class="priority"><span class="ordinal">0${n+1}</span><div>${meta(i)}<h3 style="margin-top:10px">${e(i.title)}</h3><p class="finish">${e(i.next_action||i.body)}</p>${i.focus_on&&i.focus_on<board.today?`<p class="small">Carried from ${e(dateLabel(i.focus_on))}. Keep, finish or park it.</p>`:''}${actions(i)}</div></article>`).join(''):'<p class="empty">No priorities have been selected for this day. Choose Today on an open task, or add one below. Nothing is invented to fill the space.</p>'}</div>${agents.length?`<details class="changes"><summary>Agent queue · ${agents.length} open</summary><p class="small">Saved work for the next authorized agent session. This list does not itself run background jobs.</p>${agents.map(itemMarkup).join('')}</details>`:''}</div><aside><section class="side-panel"><div class="section-head"><h2>Next commitments</h2></div>${upcoming.length?upcoming.map(appointmentMarkup).join(''):'<p class="empty">No appointment projection is available for this window. Check Calendar rather than assuming you are free.</p>'}<p class="source-note">${calendar?`Calendar checked ${e(checked(calendar.observed_at))}. ${sourceState(calendar)==='stale'?'This copy needs refreshing.':''}`:'Calendar has not been checked.'} This is a saved projection, not a live free/busy check.</p><a class="ref" href="https://calendar.google.com/calendar/u/0/r" target="_blank" rel="noopener">Open Calendar ↗</a></section>${personal.length?`<section class="side-panel"><h2 style="margin-bottom:18px">My training</h2>${personal.map(itemMarkup).join('')}</section>`:''}<section class="side-panel"><h2>Not another list to finish</h2><p class="small">Waiting stays out of your top four. The rest of life stays visible in All areas. Done means the action happened, not that its calendar slot passed.</p></section></aside></div>`;
}
function areasView(){
  const selected=area==='all'?Object.keys(AREAS):[area];
  return `<div class="area-tabs"><button type="button" data-area="all" class="${area==='all'?'active':''}">All</button>${Object.entries(AREAS).map(([k,v])=>`<button type="button" data-area="${k}" class="${area===k?'active':''}">${e(v)}</button>`).join('')}</div><div class="area-grid">${selected.map(k=>{const items=board.items.filter(i=>i.area===k&&!closed(i));return `<section class="panel ${selected.length===1?'wide':''}"><h2 style="margin-bottom:25px">${e(AREAS[k])}</h2>${items.length?items.map(itemMarkup).join(''):'<p class="empty">No open operating items recorded.</p>'}${k==='coaching'?coachingView():''}</section>`;}).join('')}</div><details class="changes"><summary>Recently closed</summary>${board.items.filter(closed).slice().sort((a,b)=>b.updated_at.localeCompare(a.updated_at)).slice(0,12).map(itemMarkup).join('')||'<p class="empty">No closed items recorded yet.</p>'}</details>`;
}
function coachingView(){return `<h3 class="split-label">Current coach decisions · live FORM records</h3>${board.decisions.map(d=>`<article class="decision"><div class="metadata"><b>${e(athleteName(d.athlete_id))}</b><span>Effective ${e(dateLabel(d.effective_on))}</span><span>${d.delivery_state==='delivered_externally'?'Delivered directly':'Published'}</span></div><p>${e(d.athlete_text)}</p></article>`).join('')||'<p class="empty">No current published decisions returned. This does not mean no assignment exists.</p>'}${board.coach_tasks.length?`<h3 class="split-label">Open coaching gates</h3>${board.coach_tasks.map(coachTask).join('')}`:''}${board.coach_todos.length?`<h3 class="split-label">Dossier to-dos</h3>${board.coach_todos.map(t=>`<div class="item"><b>${e(athleteName(t.athlete_id))}</b><p>${e(t.body)}</p>${t.due_on?`<p class="small">Due ${e(dateLabel(t.due_on))}</p>`:''}</div>`).join('')}`:''}<a class="ref" href="/coach/labs/">Open athlete dossiers ↗</a><p class="source-note">These are existing FORM records, not copied plans. Appointment timing is separate from prescribed work. A new decision does not rewrite completed evidence.</p>`;}

function monday(value){
  const d=new Date(value+'T12:00:00-04:00'), day=(d.getDay()+6)%7;
  d.setDate(d.getDate()-day);
  return d;
}
function isoDay(d){return d.toLocaleDateString('en-CA',{timeZone:'America/New_York'});}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x;}
function daysBetween(a,b){return Math.round((new Date(b+'T12:00:00-04:00')-new Date(a+'T12:00:00-04:00'))/86400000);}
function horizonState(block){
  if(!block?.ends_on)return {label:'Term not dated',className:'warning'};
  const n=daysBetween(board.today,block.ends_on);
  if(n<0)return {label:'Needs closeout',className:'warning'};
  if(n<=7)return {label:'This week',className:'warning'};
  if(n<=21)return {label:'Ending soon',className:'warning'};
  return {label:'Active',className:''};
}
function runwayView(){
  const start=monday(board.today), weeks=Array.from({length:12},(_,i)=>{const s=addDays(start,i*7),e=addDays(s,6);return {start:isoDay(s),end:isoDay(e),label:s.toLocaleDateString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric'})};});
  const tasks=board.items.filter(i=>i.kind==='task'&&!closed(i));
  const dated=tasks.filter(i=>i.due_on||i.review_on||i.focus_on);
  const backlog=tasks.filter(i=>!i.due_on&&!i.review_on&&!i.focus_on).slice().sort((a,b)=>a.priority-b.priority).slice(0,12);
  const cell=(w)=>dated.filter(i=>{const d=i.due_on||i.review_on||i.focus_on;return d>=w.start&&d<=w.end;}).slice(0,6).map(i=>`<button type="button" class="runway-card" data-action="edit" data-id="${e(i.id)}"><span>${e(AREAS[i.area]||i.area)}</span><b>${e(i.title)}</b><small>${i.due_on?'Due ':i.review_on?'Review ':'Focus '}${e(dateLabel(i.due_on||i.review_on||i.focus_on))}</small></button>`).join('');
  const blocks=board.athlete_blocks||[];
  return `<section class="runway-intro"><div><p class="eyebrow">Company runway</p><h2>See the next 12 weeks.</h2><p>Dates come from the operating workspace. Athlete horizons come live from FORM. Scroll sideways like a training plan; click an operating card to edit its next step.</p></div><div class="hat-key"><span>COACH</span><span>PRACTICE HOST</span><span>PRODUCT DIRECTOR</span><span>BUILDER / REVIEWER</span><span>CREATIVE DIRECTOR</span><span>COMMERCIAL LEAD</span><span>OPERATOR</span><span>STUDENT / ATHLETE</span></div></section>
  <div class="runway-scroll" tabindex="0" aria-label="Twelve week company runway"><div class="runway-grid">${weeks.map(w=>`<section class="runway-week"><header><b>WEEK OF</b><span>${e(w.label)}</span></header>${cell(w)||'<p class="empty-mini">Open capacity</p>'}</section>`).join('')}</div></div>
  <div class="runway-split"><section class="panel"><div class="section-head"><h2>Athlete horizons</h2><span class="small">Review at 21 days</span></div>${blocks.length?blocks.map(b=>{const s=horizonState(b);return `<article class="horizon"><div><b>${e(b.first_name||'Athlete')}</b><span class="pill ${s.className}">${e(s.label)}</span></div><p>${e(b.name||'No dated active block')}${b.current_week&&b.total_weeks?` · Week ${e(b.current_week)} of ${e(b.total_weeks)}`:''}</p><small>${b.ends_on?`Ends ${e(dateLabel(b.ends_on,{month:'short',day:'numeric',year:'numeric'}))}`:'No block end date in FORM'}${b.race_on?` · Race ${e(dateLabel(b.race_on))}`:''}</small></article>`;}).join(''):'<p class="empty">No athlete horizon projection returned.</p>'}</section>
  <section class="panel"><div class="section-head"><h2>Undated work</h2><span class="small">Backlog, not today</span></div>${backlog.length?backlog.map(itemMarkup).join(''):'<p class="empty">No undated operating work.</p>'}</section></div>`;
}
function waitingView(){const items=board.items.filter(i=>i.status==='waiting');const tasks=board.coach_tasks.filter(t=>t.state.startsWith('waiting'));return `<div class="layout"><section><div class="section-head"><h2>Someone or something else moves next</h2></div>${items.map(itemMarkup).join('')}${tasks.map(coachTask).join('')}${!items.length&&!tasks.length?'<p class="empty">No waiting items recorded.</p>':''}</section><aside class="side-panel"><h2>Keep the next question small</h2><p>Name who you are waiting for, what they need to supply and when you will check again. A time-pending agreement is not a confirmed clock-time appointment.</p></aside></div>`;}
function sourcesView(){return `<p class="intro" style="margin:26px 0">Know what is live, what was checked and what is still unresolved.</p><div class="source-list">${board.sources.map(s=>{const st=sourceState(s);return `<article class="source"><div><h3>${e(s.label)}</h3><span class="pill ${['stale','conflict','unavailable','pending','unchecked'].includes(st)?'warning':''}">${e(sourceName(st))}</span></div><div><p><b>Owns:</b> ${e(s.authority)}</p><p>${e(s.detail)}</p><p class="small">Checked ${e(checked(s.observed_at))}.${s.source_as_of?` Source data through ${e(checked(s.source_as_of))}.`:' Source data-as-of is not supplied.'}</p><p class="locator">${e(s.locator)}</p></div></article>`;}).join('')}</div><section class="panel"><h2>The write-through rule</h2><p>Change the owning record first. Read it back. Record the receipt here. The brief reads this same workspace, plus fresh evidence from its original connectors. A link or a saved note never proves every destination synchronized.</p><p class="source-note">FORM decisions and coaching tasks are read live. Calendar, Finances, GitHub, Gmail and wearable checks are refreshed by authorized connector work, not by this browser's Refresh button. No bank token, private record or service-role key is embedded in this site.</p></section><details class="changes"><summary>Recent saved changes</summary><ul>${board.changes.map(c=>`<li>${e(c.title||c.label||'Operating record')} · ${e(c.status?statusName(c.status):c.operation.toLowerCase())}<br><span class="small">${e(checked(c.changed_at))} · revision ${e(c.revision||'1')}</span></li>`).join('')}</ul></details>`;}
function render(){
  if(!board)return;
  $('#gate').hidden=true;$('#workspace').hidden=false;$('#refresh').hidden=false;$('#signout').hidden=false;
  $('#date').textContent=dateLabel(board.today,{weekday:'long',month:'long',day:'numeric',year:'numeric'});
  $('#page-title').textContent={today:'Today.',runway:'Runway.',areas:'Everything has a place.',waiting:'Waiting.',sources:'What is current?'}[tab];
  $('#freshness').textContent=`Workspace read ${checked(board.read_at)} ET`;
  $('#waiting-count').textContent=board.items.filter(i=>i.status==='waiting').length+board.coach_tasks.filter(t=>t.state.startsWith('waiting')).length;
  $('#source-count').textContent=board.sources.filter(s=>['stale','conflict','unavailable','pending','unchecked'].includes(sourceState(s))).length||'';
  $('[data-tab][aria-current]')?.removeAttribute('aria-current');$(`[data-tab="${tab}"]`).setAttribute('aria-current','page');
  $('#view').innerHTML=({today:todayView,runway:runwayView,areas:areasView,waiting:waitingView,sources:sourcesView}[tab])();
}
async function refresh(){
  if(loading||!user)return;loading=true;$('#refresh').disabled=true;
  const generation=authGeneration;
  try{const {data,error}=await supabase.rpc('operating_console_read',{});if(error)throw error;if(generation!==authGeneration)return;board=validateBoard(data);render();message('');return true;}
  catch(err){if(generation!==authGeneration)return;if(!board){$('#gate').hidden=false;$('#workspace').hidden=true;$('#signout').hidden=false;$('#gate-message').textContent='This account could not open the private operating workspace. Use the authorized coach account, or retry if the connection is unavailable.';}else{message('Refresh failed. The last successfully loaded workspace is still shown. Its source timestamps have not changed.',true);}}
  finally{if(generation===authGeneration){loading=false;$('#refresh').disabled=false;}else if(user){loading=false;queueMicrotask(refresh);}}
}
async function sessionChanged(session){
  const next=session?.user||null;
  if(next?.id===user?.id){if(next&&!board&&!loading)await refresh();return;}
  authGeneration++;user=next;board=null;$('#editor').close();$('#edit-form').reset();$('#capture-form').reset();message('');$('#view').replaceChildren();$('#workspace').hidden=true;
  $('#gate').hidden=false;$('#refresh').hidden=true;$('#signout').hidden=!user;
  $('#gate-message').textContent=user?'Opening your private workspace.':'Sign in with your existing coach account.';
  if(user&&!loading)await refresh();
}
async function saveItem(item,patch){const {data,error}=await supabase.from('operating_items').update(patch).eq('id',item.id).eq('revision',item.revision).select('id,revision').maybeSingle();if(error)throw error;if(!data)throw new Error('This record changed elsewhere. Refresh and review it before saving again.');const reread=await refresh();if(!reread)throw new Error('Saved on the server, but the workspace could not reload. Refresh before making another change.');return data;}
$('#view').addEventListener('click',async event=>{
  const areaButton=event.target.closest('[data-area]');if(areaButton){area=areaButton.dataset.area;render();return;}
  const button=event.target.closest('button[data-action]');if(!button||!board)return;
  const item=board.items.find(i=>i.id===button.dataset.id);if(!item)return;
  if(button.dataset.action==='edit'){const f=$('#edit-form');for(const key of ['id','revision','title','next_action','body','status','priority','due_on','waiting_on','review_on','area','actor','focus_on'])f.elements[key].value=item[key]??'';$('#edit-message').textContent='';$('#editor').showModal();return;}
  button.disabled=true;
  try{const patch=button.dataset.action==='done'?{status:'done'}:{focus_on:board.today};await saveItem(item,patch);message(button.dataset.action==='done'?'Saved as done. No appointment, payment or prescription was changed.':'Selected for today. The first four ready items are shown.');}catch(err){message(err.message||'Not saved. Please retry.',true);button.disabled=false;}
});
$('.tabs').addEventListener('click',ev=>{const b=ev.target.closest('[data-tab]');if(!b)return;tab=b.dataset.tab;render();});
$('#refresh').addEventListener('click',refresh);
$('#signout').addEventListener('click',async()=>{const {error}=await supabase.auth.signOut();if(error){message('Sign-out failed. Please retry.',true);return;}await sessionChanged(null);});
$('#signin-form').addEventListener('submit',async ev=>{ev.preventDefault();const form=ev.target;const b=form.querySelector('[type=submit]');b.disabled=true;try{if(!form.elements['password'].value)throw new Error('Enter your password, or choose a sign-in link.');await signInWithPassword(form.elements['email'].value,form.elements['password'].value);form.elements['password'].value='';}catch(err){$('#gate-message').textContent=err.message||'Sign-in failed.';}finally{b.disabled=false;}});
$('#magic').addEventListener('click',async()=>{const f=$('#signin-form');if(!f.elements['email'].reportValidity())return;$('#magic').disabled=true;try{await sendMagicLink(f.elements['email'].value,'/coach/ops/');$('#gate-message').textContent='Sign-in link requested. Open it in this browser to return here.';}catch(err){$('#gate-message').textContent=err.message||'Could not request a link.';}finally{$('#magic').disabled=false;}});
$('#capture-form').addEventListener('submit',async ev=>{ev.preventDefault();if(!user||!board)return;const f=ev.target,b=f.querySelector('[type=submit]');b.disabled=true;try{const title=f.elements['title'].value.trim();if(!title)throw new Error('Give the task a concrete title.');const {data,error}=await supabase.from('operating_items').insert({owner_id:user.id,item_key:`capture-${crypto.randomUUID()}`,kind:'task',area:f.elements['area'].value,title,next_action:f.elements['next_action'].value.trim(),actor:f.elements['actor'].value,due_on:f.elements['due_on'].value||null,focus_on:f.elements['focus'].checked?board.today:null,source_refs:[{label:'Owner entered in console'}]}).select('id,revision').single();if(error)throw error;if(!data)throw new Error('Save was not confirmed.');f.reset();const reread=await refresh();message(reread?'Saved to the shared operating workspace.':'Saved on the server. Workspace reload failed; refresh before adding another copy.',!reread);}catch(err){message(err.message||'Not saved.',true);}finally{b.disabled=false;}});
$('#close-editor').addEventListener('click',()=>$('#editor').close());
$('#edit-form').addEventListener('submit',async ev=>{ev.preventDefault();const f=ev.target,b=f.querySelector('[type=submit]');const item=board?.items.find(i=>i.id===f.elements['id'].value);if(!item)return;b.disabled=true;try{const patch={area:f.elements['area'].value,actor:f.elements['actor'].value,focus_on:f.elements['focus_on'].value||null,title:f.elements['title'].value.trim(),next_action:f.elements['next_action'].value.trim(),body:f.elements['body'].value.trim(),status:f.elements['status'].value,priority:Number(f.elements['priority'].value),due_on:f.elements['due_on'].value||null,waiting_on:f.elements['waiting_on'].value.trim()||null,review_on:f.elements['review_on'].value||null};if(!patch.title)throw new Error('Title is required.');if(patch.status==='waiting'&&!patch.waiting_on)throw new Error('Name who or what you are waiting on.');await saveItem({...item,revision:Number(f.elements['revision'].value)},patch);$('#editor').close();message('Changes saved and read back.');}catch(err){$('#edit-message').textContent=err.message||'Not saved.';}finally{b.disabled=false;}});
supabase.auth.onAuthStateChange((_event,session)=>queueMicrotask(()=>sessionChanged(session)));
const initial=await supabase.auth.getSession();
await sessionChanged(initial.data?.session||null);
if(!user)$('#gate-message').textContent='Sign in with your existing coach account.';
