'use strict';
// Authored public guidance, not an athlete assignment or an automatically generated plan.
const ref = n => `<a class="guide-ref" href="#source-${n}" aria-label="Source ${n}">[${n}]</a>`;
const section=(id,title,html)=>({id,title,html});
const faq=(q,a)=>`<details class="guide-detail"><summary>${q}</summary><div>${a}</div></details>`;
const signals=(items)=>`<div class="guide-signals">${items.map(([title,text])=>`<div><h3>${title}</h3><p>${text}</p></div>`).join('')}</div>`;
const steps=(items)=>`<ol class="guide-steps">${items.map(([n,title,text])=>`<li><span class="guide-step-number">${n}</span><div><h3>${title}</h3><p>${text}</p></div></li>`).join('')}</ol>`;
module.exports = [
{
 file:'easy-run.html',route:'/easy-run',number:'01',label:'Easy running',
 title:'Easy Running: How Easy, How Long & Why It Matters | FORM',
 heading:'How easy should an easy run feel?',
 description:'Use conversation, effort, and recovery to keep easy runs easy. A practical session example, common adjustments, and clear guidance for hot or tired days.',
 answer:'Easy enough to hold a comfortable conversation. You should finish with room to keep going, not feel as though you have completed a workout.',
 summary:'Run at an effort you can repeat. Let the pace change with the day.',
 sections:[
 section('effort','Start with effort. Check the pace second.',`<p>On an easy run, speak a few full sentences without having to organize each one around a breath. You are still exercising; breathing faster than at rest is normal. The useful distinction is whether conversation feels comfortable. The talk test is a practical guide, not a laboratory measurement of your training zones. ${ref(1)} ${ref(2)}</p>
 ${signals([['Breathing','Full sentences, comfortably.'],['Movement','A rhythm you do not have to force.'],['Finish','You could continue, but the run is done.']])}
 <p>A slower pace than your friend’s is not a problem to solve. Neither is a slower pace than last week’s. Use the effort you have today.</p>`),
 section('purpose','Easy running is training, not filler.',`<p>Lower-intensity running lets you accumulate endurance work without making every session a hard one. Research supports giving a substantial part of an endurance runner’s training to lower-intensity work. It does not establish one perfect percentage for every runner. ${ref(3)}</p><p>In FORM, I use easy days to support the work around them. A run that leaves you too tired for the rest of the week has missed that job, even when the average pace looks good.</p><p>Easy and recovery are not synonyms. A long run can be easy in intensity and still be a substantial load because of its duration.</p>`),
 section('example','A simple easy run.',`<figure class="guide-example"><figcaption>Session example · For someone already comfortable running 30 minutes</figcaption><div class="guide-example-title"><strong>30 <span>minutes</span></strong><span>Conversation throughout</span></div>
 ${steps([['05','Ease into it','Start gently. There is no pace to catch up to.'],['20','Find your rhythm','Keep conversation comfortable, including on hills.'],['05','Finish easily','Do not add a fast finish just to improve the average.']])}</figure>
 <p>Thirty minutes is an example, not an entry requirement. Use a duration you already handle. Short runs and planned walking breaks are legitimate ways to build the practice.</p>`),
 section('adjust','When easy does not feel easy.',`<dl class="guide-decisions"><div><dt>You can only say a few words.</dt><dd>Slow down or walk until conversation is comfortable. Do not defend the number on your watch.</dd></div><div><dt>It is hotter or more humid.</dt><dd>Choose a cooler time or shaded route, adjust the pace, and shorten the run when needed. Heat adds physiological strain; yesterday’s pace is not today’s obligation. ${ref(4)}</dd></div><div><dt>Your legs are heavy from training.</dt><dd>Try a shorter, gentler run or rest. Easy running is not a requirement to run through accumulated fatigue.</dd></div><div><dt>Pain appears or changes your stride.</dt><dd>Stop the run rather than trying to coach yourself through it. Persistent or recurring pain needs assessment. ${ref(5)}</dd></div></dl>`),
 section('questions','Questions that come up.',faq('Should I stay in Zone 2?',`<p>Use the definition behind the zone, not just its name. Zone systems and watch settings differ. Comfortable speech and manageable effort are useful checks alongside heart rate; neither is a substitute for an individualized threshold assessment. ${ref(1)} ${ref(2)}</p>`)+faq('Will running slowly make me slow?',`<p>Easy running is one part of a training week, not the whole prescription. Keep easy days easy, then put purposeful faster work where your training supports it. Read <a href="/threshold-training">the threshold guide</a> for that different job.</p>`)+faq('How do I know it is working?',`<p>Look for repeatable weeks and an effort you can manage, not a personal best on every easy run. Compare similar routes and conditions over time. A single unusually fast or low-heart-rate run does not establish a new fitness level.</p>`))
 ],
 sources:[
 ['Persinger et al. (2004)','Consistency of the talk test for exercise prescription','https://pubmed.ncbi.nlm.nih.gov/15354048/','Supports speaking comfort as an intensity guide in a small laboratory study.'],
 ['Rotstein et al. (2004)','Perceived speech difficulty during exercise and its relation to exercise intensity and physiological responses','https://pubmed.ncbi.nlm.nih.gov/15221401/','Found substantial individual variation. Speech is not a precise substitute for physiological testing.'],
 ['Esteve-Lanao et al. (2007)','Impact of training intensity distribution on performance in endurance athletes','https://pubmed.ncbi.nlm.nih.gov/17685689/','A small randomized study of subelite runners; supports substantial low-intensity work, not a universal weekly ratio.'],
 ['Racinais et al. (2015)','Consensus recommendations on training and competing in the heat','https://pubmed.ncbi.nlm.nih.gov/26069301/','Heat adds strain. Conditions and preparation matter.'],
 ['NHS','Knee pain and other running injuries','https://www.nhs.uk/live-well/exercise/knee-pain-and-other-running-injuries/','General injury guidance and when to stop or seek assessment.']
 ],
 related:[['/threshold-training','Add a purposeful harder day','Threshold effort and a session example.'],['/long-run-pace','Carry easy effort farther','How to approach the longer run.'],['/library/easy-days/','When easy days keep getting hard','A closer look at the recurring problem.']],
 help:'Not sure where easy ends for you?',helpText:'Tell me what your running week looks like and what you are training for. We can start with the work you actually do, not the pace you think you should run.'
},
{
 file:'threshold-training.html',route:'/threshold-training',number:'02',label:'Threshold training',
 title:'Threshold Running: Effort, Workouts & Progression | FORM',
 heading:'Run strong. Keep it controlled.',
 description:'Understand threshold running, choose a manageable session, and know when to adjust. Controlled effort, practical examples, and the difference from race pace.',
 answer:'Threshold work is sustained, demanding running that stays controlled. The aim is useful time at a strong effort, not the fastest possible final repetition.',
 summary:'Finish the work without turning the session into a race.',
 sections:[
 section('effort','What the effort should feel like.',`<p>Breathing is deeper than on an easy run. Short phrases are possible, but conversation is no longer relaxed. You are concentrating on the work without fighting to complete each minute. Those are coaching cues, not a blood-lactate test.</p>
 ${signals([['Easy running','You can talk comfortably.'],['Threshold work','Strong, focused, controlled.'],['Too hard for this job','You are racing the last repetition.']])}
 <p>Some increase in effort as a session progresses is normal. Repeated slowing, straining, or needing much longer rests is a reason to adjust. Do not turn “controlled” into a requirement that every repetition feels identical.</p>`),
 section('meaning','What “threshold” means here.',`<p>Coaches use the word threshold in different ways. Here it means controlled sustained work near the upper end of your sustainable aerobic effort. Physiological threshold methods do not all identify the same speed, and the first rise in blood lactate is not the same boundary as the highest sustainable steady state. ${ref(1)}</p><p>Lactate is not waste you need to flush out. It is also a fuel used during exercise. Fatigue cannot be reduced to a single substance or a line on a watch. ${ref(2)}</p><p>The practical coaching goal is to develop sustained running with a dose you can recover from. Threshold is part of the training, not a guarantee of improvement at every race distance.</p>`),
 section('session','Start with a session you can control.',`<figure class="guide-example"><figcaption>Session example · For a runner already training consistently and ready for faster work</figcaption><div class="guide-example-title"><strong>3 × 6 <span>minutes</span></strong><span>18 minutes of strong running</span></div><div class="guide-intervals" aria-label="Six minutes strong, two minutes easy, six strong, two easy, six strong"><div>6 min<strong>Strong</strong></div><span>2 min<br>easy</span><div>6 min<strong>Strong</strong></div><span>2 min<br>easy</span><div>6 min<strong>Strong</strong></div></div><p class="guide-example-note">15 minutes easy before. 2 minutes easy jogging between repetitions. 10 minutes easy after. Total: 47 minutes.</p></figure><p>Keep the first repetition restrained. Use a recent, established training pace as a starting point, then adjust for effort and conditions. Do not calculate threshold from a race time you hope to run.</p><p>For someone new to running or returning after a break, consistent easy running comes first.</p>`),
 section('progress','Progress the work, not the struggle.',`<dl class="guide-decisions"><div><dt>The repetitions stay controlled and recovery is good.</dt><dd>Repeat the session. Later, extend the work a little before asking for more speed. Change one demand at a time.</dd></div><div><dt>You start too fast.</dt><dd>Slow the next repetition. Finishing the planned volume is less important than recovering the intended effort.</dd></div><div><dt>You cannot recover between repetitions.</dt><dd>Reduce the remaining work or finish easily. Longer rests change the session; they do not make an unsustainable pace the right target.</dd></div><div><dt>Heat, hills, or fatigue change the pace.</dt><dd>Keep the purpose. Adjust pace or duration instead of forcing cool-weather numbers. ${ref(3)}</dd></div></dl><p>One threshold day is a useful starting structure in my coaching, supported by easier work around it. More experienced athletes can use other arrangements. Tuesday is a scheduling choice, not a physiological rule.</p>`),
 section('questions','Threshold, tempo, and race pace.',faq('Is a tempo run the same thing?',`<p>Not always. “Tempo” is used for everything from moderately steady running to threshold work. Check the actual effort, duration, and recovery rather than treating the labels as interchangeable.</p>`)+faq('Is threshold my half-marathon pace?',`<p>Not automatically. Race pace depends on the race distance and how long you take to cover it. A faster runner and a slower runner can race the same distance at different intensities relative to their thresholds. Establish your own pace instead of applying one fixed gap to everyone.</p>`)+faq('Should I finish as fast as I can?',`<p>No. Finish the prescribed work. A sprint at the end answers a different question from the one this session asks. Save the race effort for an appropriate session or the race itself.</p>`))
 ],
 sources:[
 ['Faude, Kindermann & Meyer (2009)','Lactate threshold concepts: how valid are they?','https://pubmed.ncbi.nlm.nih.gov/19453206/','Reviews distinct threshold definitions. A coaching effort cue cannot identify an exact laboratory boundary.'],
 ['Emhoff et al. (2013)','Direct and indirect lactate oxidation in trained and untrained men','https://pubmed.ncbi.nlm.nih.gov/23788576/','Human tracer research demonstrating lactate use as an exercise fuel.'],
 ['Racinais et al. (2015)','Consensus recommendations on training and competing in the heat','https://pubmed.ncbi.nlm.nih.gov/26069301/','Guidance on the added strain of hot conditions.']
 ],
 related:[['/easy-run','Protect the easier days','What easy effort should feel like.'],['/long-run-pace','Plan the longer run','Duration and intensity are separate demands.'],['/labs/track/','Explore the actual sessions','Authored track workouts and execution standards.']],
 help:'A strong pace is only useful when the dose fits.',helpText:'Coaching connects the session to your current running, your recovery, and the race ahead. Tell me what you are preparing for.'
},
{
 file:'long-run-pace.html',route:'/long-run-pace',number:'03',label:'The long run',
 title:'Long-Run Pacing: Effort, Duration & Strong Finishes | FORM',
 heading:'Run farther without racing the distance.',
 description:'Choose a manageable long run, separate easy effort from steady finishes, and adjust when fatigue or heat changes the day. Examples for a repeatable training week.',
 answer:'Most long runs begin at an easy, conversational effort. Choose a duration that fits your recent training. A faster finish is an optional training choice, not the price of a good long run.',
 summary:'Build the duration you can handle before adding more demand.',
 sections:[
 section('purpose','Long is a demand of its own.',`<p>A run does not need to be fast to be demanding. More time on your feet changes its cost. Research shows that physiological responses can change as running continues, and that trained and less-trained runners do not respond identically. ${ref(1)}</p><p>The long run gives you practice holding a manageable effort for longer, making pacing decisions, and learning what food, drink, and equipment work for you. The whole run matters. Adaptation does not switch on at minute 50.</p>`),
 section('choose','Choose the job before the pace.',`<div class="guide-compare"><section><h3>All easy</h3><p>Build time on your feet at conversational effort.</p><div class="guide-bar" role="img" aria-label="An easy effort from start to finish"><span style="flex:1">Easy throughout</span></div><p class="guide-small">The first choice when extending your duration, returning to the routine, or managing a demanding week.</p></section><section><h3>Easy, then steady</h3><p>Add a deliberate finish below threshold effort.</p><div class="guide-bar" role="img" aria-label="An easy first portion followed by a shorter steady portion"><span style="flex:3">Easy</span><span class="guide-bar-work" style="flex:1">Steady</span></div><p class="guide-small">A planned progression for someone already comfortable with the duration. It is not required every week.</p></section></div><p class="guide-caption">Illustration of two session structures, not measured pace data or a fixed ratio.</p><p>Steady is more purposeful than easy, without becoming threshold work. No fixed number of seconds slower than threshold identifies the right long-run pace for every athlete. Use your established running, the purpose of the day, and your response.</p>`),
 section('duration','Start with a duration you already handle.',`<p>Begin near a duration you have recently completed comfortably. Repeat it before extending it. Do not increase distance and add a harder finish in the same step. Gradual increases and repeated exposure are more sensible than treating a weekly percentage as a safety guarantee. ${ref(2)}</p><figure class="guide-example"><figcaption>Session example · For someone already comfortable with runs near one hour</figcaption><div class="guide-example-title"><strong>60 <span>minutes</span></strong><span>All easy. No finish to earn.</span></div>${steps([['10','Settle in','Start below the effort you intend to hold.'],['40','Keep it conversational','Let the pace follow the terrain and the day.'],['10','Finish with control','Keep the same easy purpose. Do not race home.']])}</figure><p>If 30 minutes is currently your longer run, there is no need to jump to an hour. If you already handle much longer runs, the next step depends on your race and the rest of your week. This is a way to choose, not a universal mileage prescription.</p>`),
 section('finish','Make the finish a decision, not a dare.',`<dl class="guide-decisions"><div><dt>The run is comfortable and the plan says easy.</dt><dd>Keep it easy. Feeling good does not require an upgrade.</dd></div><div><dt>A steady finish was planned and you still feel controlled.</dt><dd>Move up gradually. Keep the finish within its assigned effort and duration; do not chase a best split.</dd></div><div><dt>Breathing keeps rising or your stride starts to deteriorate.</dt><dd>Drop the faster finish, slow down, or shorten the run. Review pace, duration, conditions, and fueling afterward instead of diagnosing the cause mid-run.</dd></div><div><dt>You started too fast.</dt><dd>Slow down now. The start cannot be undone, but the remaining run can still be adjusted. One mistake does not mean the session or your aerobic system is damaged.</dd></div></dl>`),
 section('prepare','Practice the practical things.',`<p>On longer outings, plan access to drink and take the fuel you intend to practice with. Use familiar choices and learn during training rather than making race day the first attempt. Nutrition needs depend on the duration, intensity, conditions, and your tolerance. ${ref(3)}</p><p>In heat, adjust timing, route, pace, and duration. Do not turn an easy-effort run into a heat test. ${ref(4)} Stop if pain changes your stride; persistent or recurring pain needs assessment. ${ref(2)}</p><p>Afterward, note the duration, how the finish felt, what you ate or drank, and how you recovered. Use the next day’s response when deciding whether to repeat or extend the run.</p>`),
 section('questions','Questions that come up.',faq('Do I need a fast finish every week?',`<p>No. An all-easy long run has a clear job. A faster finish adds intensity to duration and needs room in the wider training week.</p>`)+faq('Does the long run have to be on Saturday?',`<p>No. Choose a day that gives the run and your recovery enough space. Keep a useful routine without treating a weekday as a training adaptation.</p>`)+faq('Should a half-marathon long run be 13.1 miles?',`<p>There is no single required distance for every runner. Choose from recent volume, time on feet, race expectations, and recovery. Completing race distance in training is not a prerequisite for every first half marathon.</p>`))
 ],
 sources:[
 ['Unhjem (2024)','Changes in running economy and attainable maximal oxygen consumption in response to prolonged running: The impact of training status','https://pubmed.ncbi.nlm.nih.gov/38671555/','A one-hour laboratory comparison. Supports individual differences under duration, not a particular long-run prescription.'],
 ['NHS','Knee pain and other running injuries','https://www.nhs.uk/live-well/exercise/knee-pain-and-other-running-injuries/','Gradual progression and general injury guidance.'],
 ['Thomas, Erdman & Burke (2016)','Nutrition and Athletic Performance','https://pubmed.ncbi.nlm.nih.gov/26920240/','Position statement on individualizing food, fluid, and fuel for exercise.'],
 ['Racinais et al. (2015)','Consensus recommendations on training and competing in the heat','https://pubmed.ncbi.nlm.nih.gov/26069301/','Heat preparation, hydration, and physiological strain.']
 ],
 related:[['/easy-run','Check your easy effort','Conversation before a pace target.'],['/threshold-training','Keep strong work distinct','Threshold is a different training job.'],['/library/first-half-marathon-goal/','Choose a half-marathon goal','Start with your recent running.']],
 help:'The right long run belongs to a whole week.',helpText:'Tell me your recent longest run, how you recovered, and what you are preparing for. That is a better starting point than choosing a distance in isolation.'
},
{
 file:'running-form-errors.html',route:'/running-form-errors',number:'04',label:'Running form',
 title:'Running Form: What to Change, What to Leave Alone | FORM',
 heading:'Not everything needs fixing.',
 description:'Learn what to notice in your running form, how to test one useful cue, and when to leave a movement alone. Includes cadence practice without a universal target.',
 answer:'Start with something that is costing you effort, comfort, or control. Change one thing, then compare. A movement does not need correcting just because it looks different.',
 summary:'Notice the cost. Try one change. Keep only what helps.',
 sections:[
 section('notice','Start with the runner, not the screenshot.',`<p>Ask what you feel and when it appears. Tension from the first minute is a different coaching question from a rhythm that changes late in a hard run. A video helps you observe movement; it does not diagnose weakness, injury, or running economy by itself.</p>${steps([['01','Notice','Name a specific feeling or difficulty. Observe it at a known pace.'],['02','Try','Use one small cue at easy effort. Keep the comparison fair.'],['03','Check','Does it feel easier or more repeatable without a new problem?']])}<p>A useful change should survive more than one promising minute. Recheck it on another day before treating it as established.</p>`),
 section('observations','Find the observation that fits.',`<p>These are starting points for a coaching experiment, not diagnoses. Leave comfortable, repeatable movement alone.</p>
 <details class="guide-detail" id="overstriding"><summary>You feel as though each step brakes.</summary><div><p><strong>Notice:</strong> Is the sensation still present when you slow down? A foot landing ahead of you in a side-view image is not, by itself, proof of a problem.</p><p><strong>Try:</strong> “Shorter, easier steps.” Keep the speed easy instead of speeding up to increase your step rate. Small step-rate increases changed several measures of knee and hip loading in a laboratory study; that is not proof of injury prevention or better performance for every runner. ${ref(1)}</p><p><strong>Check:</strong> Less reaching or jarring, without extra calf tension. Do not force the foot directly under your hips.</p></div></details>
 <details class="guide-detail" id="hip-collapse"><summary>One side feels less controlled.</summary><div><p><strong>Notice:</strong> When does it appear, and does it persist at an easier pace? A visible hip drop does not establish that a particular muscle is weak or “not firing.”</p><p><strong>Try:</strong> Reduce the pace first. Use a simple cue such as “tall and balanced” rather than locking the pelvis rigid.</p><p><strong>Check:</strong> Whether the movement feels more controlled and repeatable. Persistent pain or a new limp belongs with a qualified clinician, not a guessed exercise diagnosis. ${ref(4)}</p></div></details>
 <details class="guide-detail" id="heel-strike"><summary>You are worried about landing on your heel.</summary><div><p><strong>Notice:</strong> Heel contact is a description, not a diagnosis. Do not switch your foot strike just to resemble another runner.</p><p><strong>Understand:</strong> Different foot-strike patterns distribute load differently. In a study of habitual patterns, forefoot runners had lower kneecap-joint loading but greater Achilles-tendon loading. The comparison does not show that switching prevents injury. ${ref(2)}</p><p><strong>Check:</strong> Comfort and control at your normal easy pace. A new foot strike is not automatically a better one.</p></div></details>
 <details class="guide-detail" id="arm-crossover"><summary>Your arms feel busy or your torso twists.</summary><div><p><strong>Notice:</strong> Some arm crossover and trunk rotation are part of running. The reason to investigate is a felt cost, not a line drawn down a video.</p><p><strong>Try:</strong> Relax your hands and let the arms swing naturally. Avoid pinning your elbows to your sides or forcing a rigid forward-back track.</p><p><strong>Check:</strong> Less tension without having to keep policing every arm swing.</p></div></details>
 <details class="guide-detail" id="vertical-bounce"><summary>You feel as though you are bouncing upward.</summary><div><p><strong>Notice:</strong> Running includes vertical movement. A watch’s bounce value is not an objective grade of your form.</p><p><strong>Try:</strong> At easy speed, stop deliberately pushing upward. A slightly shorter step is another small experiment when reaching is part of the same pattern. ${ref(1)}</p><p><strong>Check:</strong> A smoother feeling without crouching, shuffling, or tensing your legs. The lowest bounce is not the target.</p><p><a href="#hip-bounce-reference">Open cadence practice →</a></p></div></details>
 <details class="guide-detail" id="forward-lean"><summary>You fold forward as you tire.</summary><div><p><strong>Notice:</strong> Compare early and later running at similar speeds. Do not infer that your glutes have stopped working from the position of your torso.</p><p><strong>Try:</strong> “Stand a little taller.” Let the ribs settle comfortably over the pelvis without arching your back or forcing an ankle lean.</p><p><strong>Check:</strong> Easier breathing and control. When the posture takes constant effort to hold, reduce the training demand instead of bracing harder.</p></div></details>
 <details class="guide-detail" id="tight-shoulders"><summary>Your shoulders or hands keep tightening.</summary><div><p><strong>Notice:</strong> Is the tension present from the start, or does it appear as effort rises?</p><p><strong>Try:</strong> Unclench the hands and let the shoulders soften. Allow your normal arm height rather than pushing the hands toward the hips.</p><p><strong>Check:</strong> Less tension at the same easy speed. If the cue needs constant effort, use less of it or leave it.</p></div></details>`),
 section('hip-bounce-reference','Cadence is a setting, not a score.',`<p>Cadence is your steps per minute, counting both feet. There is no universal 180-step requirement. At a given speed, runners often choose a step frequency close to their economical range; a number alone is not a reason to change it. ${ref(3)}</p><p>When a step-rate experiment is appropriate, begin with your natural cadence and make a small change. For example, 5% above 160 is 168, not 180. The arithmetic is an illustration, not your prescription. Keep speed comparable and stop when the change adds strain. ${ref(1)}</p>
 <details class="guide-detail guide-tool" id="cadence-practice"><summary>Open the practice metronome</summary><div><p>Choose the cadence you intend to practice. One beat is one step.</p><label for="metro-bpm">Steps per minute</label><div class="guide-tool-controls"><input id="metro-bpm" type="number" inputmode="numeric" min="100" max="220" step="1" placeholder="e.g. 164" aria-describedby="metro-status"><button id="metro-start" type="button">Start</button><button id="metro-stop" type="button" disabled>Stop</button></div><p id="metro-status" class="guide-small" role="status" aria-live="polite">Choose 100–220 steps per minute. Plays for up to 60 seconds.</p><noscript><p>Audio practice requires JavaScript. All guidance remains readable without it.</p></noscript><span id="bpm-170"></span><span id="bpm-175"></span><span id="bpm-180"></span></div></details>`),
 section('compare','Make the comparison useful.',`<div class="guide-compare"><section><h3>A useful observation</h3><p>“At the same easy speed, my shoulders felt less tense with that cue.”</p></section><section><h3>More than the evidence says</h3><p>“This cue fixed my form and made me more efficient.”</p></section></div><p class="guide-caption">Illustrative statements, not an athlete testimonial.</p><p>Separate what the runner reports, what you can see, what a device measures, and the decision you make. Heart rate during a brief comparison is not a direct measurement of running economy.</p><p>Try one cue for a short stretch, return to your usual running, then compare again. Do not rehearse a new pattern through pain. Stop and seek assessment for persistent or recurring pain, especially when it changes how you run. ${ref(4)}</p>`)
 ],
 sources:[
 ['Heiderscheit et al. (2011)','Effects of step rate manipulation on joint mechanics during running','https://pubmed.ncbi.nlm.nih.gov/20581720/','Laboratory changes at a fixed speed in 45 healthy runners. Loading effects are not the same as demonstrated injury prevention.'],
 ['Zhang et al. (2025)','Effects of habitual foot strike patterns on patellofemoral joint and Achilles tendon loading in recreational runner','https://pubmed.ncbi.nlm.nih.gov/39701021/','A comparison of habitual patterns: a load trade-off, not evidence that everyone should switch.'],
 ['Snyder & Farley (2011)','Energetically optimal stride frequency in running: the effects of incline and decline','https://pubmed.ncbi.nlm.nih.gov/21613526/','Preferred step frequency and energy cost depend on the running task.'],
 ['NHS','Knee pain and other running injuries','https://www.nhs.uk/live-well/exercise/knee-pain-and-other-running-injuries/','General guidance for painful running and seeking assessment.']
 ],
 related:[['/easy-run','Practice at an easy effort','Keep the training demand low while noticing movement.'],['/notes','See a coaching observation','An existing note from the practice.'],['/strength','Connect the running and gym work','Strength around your running week.']],
 help:'You do not have to figure out every detail alone.',helpText:'Tell me what you notice, when it happens, and what you want from your running. The first job is to understand the question, not collect more corrections.'
}
];
