'use strict';
// The smallest useful application of each lesson, with bounded examples.
module.exports={
 '/how-fast-should-i-run':{week:'Before your next familiar 20–30-minute easy run, name its job. Check conversation after 5 minutes and once near the finish; slow down if speech stops being comfortable.',mistakes:['Choosing every pace from a future race goal.','Making an easy day hard because a friend is faster.','Holding the same pace through heat or hills despite rising effort.'],fits:'Effort choice comes before workout choice. Get this right so easy days, stronger sessions and longer runs can each do their job.'},
 '/easy-run':{week:'On a run of a duration you already handle, say 2 full sentences after the first few minutes. Check again later. Slow down or walk if you have to fight for breath.',mistakes:['Chasing the same pace in different conditions.','Turning the final minute into a sprint.','Adding a longer run and treating it as cost-free because it is easy.'],fits:'Easy running is the repeatable work around the bigger demands. It builds endurance and helps you arrive ready for the sessions that matter.'},
 '/threshold-training':{week:'Already ready for controlled faster work? The 3 × 6-minute example below shows the full session: 15 easy + 6 strong + 2 easy + 6 strong + 2 easy + 6 strong + 10 easy = 47 minutes. Use your current guidance; if this effort is new, learn easy running first.',mistakes:['Racing the first repetition, then fading.','Using a dream race pace as today’s training pace.','Adding speed, more work and shorter rests together.'],fits:'Threshold is one way to practice sustained stronger running. Easy runs, long runs, fueling and recovery still have their own jobs.'},
 '/long-run-pace':{week:'Use the duration you recently handled. If 60 minutes is already familiar, the 10 + 40 + 10-minute example below keeps the entire run easy. Record the finish and how you feel the next day.',mistakes:['Adding time and a fast finish together.','Copying someone else’s longest run.','Saving your first food or drink experiment for race day.'],fits:'The long run extends time on your feet. Pace control and food-and-drink practice help you use that endurance on race day.'},
 '/sessions':{week:'Before 1 planned session this week, write 4 things: its job, the effort, the amount of work and the recovery. If any are missing, clarify the instruction before starting.',mistakes:['Assuming “intervals” means one particular speed.','Judging the session only by exhaustion.','Combining every example on this page into one week.'],fits:'Session types are the pieces of a training week. Learn the pieces here, then use the week lesson to arrange them.'},
 '/training-week':{week:'Put your next 7 days on paper. Mark the runs and any demanding lifting. The 4-run example below is for an established runner; use familiar amounts and keep easier days or rest around bigger demands.',mistakes:['Repaying a missed run by cramming it in.','Forgetting to count demanding strength work.','Adding a second workout just because another day is available.'],fits:'The week joins the individual sessions. Its job is to let you practice, recover and return, rather than win each day separately.'},
 '/running-form-errors':{week:'On 1 familiar easy run, notice what feels costly. Try 1 cue for 20–30 seconds without speeding up, let it go, then compare. Repeat another day before deciding it helped.',mistakes:['Changing several things at once.','Treating a heel strike or loud step as a diagnosis.','Forcing a universal cadence number.'],fits:'Form practice helps you explore a useful change. It sits alongside appropriate running and strength work; appearance alone cannot choose your training.'},
 '/training-principles':{week:'Review your last 3 runs. For each, name the job and how you recovered. Choose 1 useful change, or repeat what is working, rather than increasing time, speed and frequency together.',mistakes:['Treating exhaustion as proof of progress.','Changing several demands without checking the response.','Copying another runner’s progression without checking your starting point.'],fits:'These principles connect every other lesson: useful practice, manageable demand, recovery and a next step chosen from your response.'},
 '/running-terms':{week:'Take 1 session from your plan and translate it into ordinary words. For example, 3 × 6 minutes means 3 work pieces lasting 6 minutes each. Then find the effort and recovery; the numbers alone are incomplete.',mistakes:['Assuming tempo means the same effort for every coach.','Treating a watch estimate as a laboratory measurement.','Confusing pace with effort.'],fits:'The glossary helps you read plans and ask better questions. Return here when a word gets in the way of understanding the actual job.'},
 '/ghost/cues':{week:'Try 1 phrase for 20–30 seconds during a familiar easy run. Return to normal running, compare at the same speed, then check again another day.',mistakes:['Using every cue at once.','Forcing silence or nasal breathing.','Keeping a cue that adds pain or strain.'],fits:'A cue is a small experiment inside normal running. It does not replace the amount and effort your session asks for.'},
 '/mechanics-map':{week:'Describe 1 movement question after a familiar run: when it appears, at what effort, and what it costs you. Choose 1 small experiment from the linked cue lesson.',mistakes:['Diagnosing a weak muscle from one video.','Choosing a fix before describing the problem.','Treating a prettier movement as proof of better running.'],fits:'The map helps you find the right question. The linked lessons and routines help you test an answer.'},
 '/library/physique-volume/':{week:'Look at your current 7-day plan. Name 1 strength priority and count the sets assigned to it. Review the rest of the work before proposing any extra sets.',mistakes:['Adding priority work without reviewing the total.','Treating maintenance as doing nothing.','Changing exercises every week just for novelty.'],fits:'Volume is the amount of strength work within the wider week. A priority needs room, recovery and a clear reason.'},
 '/library/why-phases/':{week:'For your current training block, write 1 main priority and 2 things you are keeping in practice. Ask your coach if the reason for the current amount is unclear.',mistakes:['Changing phases only because the calendar changed.','Restoring old sets without checking the new plan.','Expecting every ability to be the main priority at once.'],fits:'Phases organize priorities over time. The daily session still tells you what to do now.'},
 '/strength':{week:'Check where lifting sits in your next 7 days. If it repeatedly makes your next run difficult, change the amount or placement with your coach. For a first session, use the small routine linked below.',mistakes:['Chasing soreness as the score.','Adding heavy work just before an important run.','Copying a trained lifter’s dose when the movements are new.'],fits:'Strength builds capacity alongside running. Both count toward the same week and need room to recover.'}
};
