/* No tracking, cookies, address-in-URL, browser persistence or implicit consent. */
(()=>{'use strict';
const $=id=>document.getElementById(id),api=document.body.dataset.api;
const version='2026-09-17-v1';let proof='',widget=null,requestId=null,lastEmail='',loading=false;
const errorText={invalid_email:'Enter a valid email address.',consent_required:'Please choose whether you would like these updates.',verification_required:'Complete the security check, then try again.',verification_unavailable:'The security check could not connect. Please try again.',rate_limited:'Please wait before requesting another email.',invalid_link:'This link is no longer available. Request a new confirmation to join.',email_unavailable:'The confirmation could not be completed. Your subscription is not active. Please try again.',unavailable:'Email updates are temporarily unavailable. Please try again later.'};
async function request(action,data){const r=await fetch(api+'/'+action,{method:data?'POST':'GET',credentials:'omit',headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(15000)});let v;try{v=await r.json();}catch{throw Error('unavailable');}if(!r.ok)throw Error(v.code||'unavailable');return v;}
function result(title,copy,label){$('signup').hidden=true;$('retry-status').hidden=true;$('token-action').hidden=true;$('unavailable').hidden=true;$('result-label').textContent=label;$('result-title').textContent=title;$('result-copy').textContent=copy;$('result').hidden=false;$('result').focus();proof='';}
function resetProof(){proof='';if(widget!==null&&window.turnstile)window.turnstile.reset(widget);}
function challenge(key){return new Promise((resolve,reject)=>{function render(){try{if(widget!==null){window.turnstile.reset(widget);resolve();return;}widget=window.turnstile.render('#challenge',{sitekey:key,action:'newsletter_signup',theme:'light',size:'flexible',callback:t=>{proof=t;},'expired-callback':()=>{proof='';},'error-callback':()=>{proof='';$('form-status').textContent=errorText.verification_unavailable;}});resolve();}catch{reject(Error('verification_unavailable'));}}
if(window.turnstile){render();return;}const old=document.getElementById('turnstile-script');old?.remove();const script=document.createElement('script');script.id='turnstile-script';script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;const timer=setTimeout(()=>{script.remove();reject(Error('verification_unavailable'));},12000);script.onload=()=>{clearTimeout(timer);render();};script.onerror=()=>{clearTimeout(timer);script.remove();reject(Error('verification_unavailable'));};document.head.appendChild(script);});}
async function init(){if(loading)return;loading=true;$('retry-status').disabled=true;try{const v=await request('status');if(v.ready!==true||typeof v.siteKey!=='string')throw Error('unavailable');$('unavailable').hidden=true;$('signup').hidden=false;await challenge(v.siteKey);$('retry-status').hidden=true;}catch(e){if($('signup').hidden){$('unavailable').hidden=false;}else $('form-status').textContent=errorText[e.message]||errorText.unavailable;$('retry-status').hidden=false;$('retry-status').disabled=false;}finally{loading=false;}}
$('retry-status').addEventListener('click',init);
$('signup').addEventListener('submit',async e=>{e.preventDefault();if(loading)return;const email=$('email').value.trim().toLowerCase();if(!$('email').checkValidity()){$('form-status').textContent=errorText.invalid_email;$('email').focus();return;}if(!$('consent').checked){$('form-status').textContent=errorText.consent_required;$('consent').focus();return;}if(!proof){$('form-status').textContent=errorText.verification_required;return;}
if(lastEmail!==email||!requestId){lastEmail=email;requestId=crypto.randomUUID();}loading=true;$('submit').disabled=true;$('form-status').textContent='Sending your request…';
try{const v=await request('subscribe',{email,consent:true,version,requestId,proof,website:$('website').value});if(v.state!=='received')throw Error('unavailable');result('Check your inbox.','If confirmation is needed, look for a message from FORM. You are only subscribed after confirming your email.','Request received');$('email').value='';$('consent').checked=false;}catch(e){$('form-status').textContent=errorText[e.message]||errorText.unavailable;resetProof();}finally{loading=false;$('submit').disabled=false;}});
const fragment=new URLSearchParams(location.hash.slice(1));const action=fragment.has('confirm')?'confirm':fragment.has('unsubscribe')?'unsubscribe':null;let token=action?fragment.get(action):null;
// Fragments never reach the server. Clear them before loading any remote service.
if(location.hash||location.search)history.replaceState(null,'',location.pathname);
if(action){document.body.classList.add('nl-managing');$('unavailable').hidden=true;$('token-action').hidden=false;const unsub=action==='unsubscribe';$('token-label').textContent='FORM email updates';$('token-title').textContent=unsub?'Leave the list?':'One last step.';$('token-copy').textContent=unsub?'Stop Field Notes, track photographs and run announcements by email. Coaching and app access are unchanged.':'Confirm that you would like occasional Field Notes, track photographs and run announcements from Brice.';$('token-button').textContent=unsub?'Unsubscribe':'Confirm my email';
if(!/^[A-Za-z0-9_-]{43}$/.test(token||'')){$('token-button').hidden=true;$('token-status').textContent=errorText.invalid_link;$('new-link').hidden=false;return;}
$('token-button').addEventListener('click',async()=>{if(loading)return;loading=true;$('token-button').disabled=true;$('token-status').textContent='';try{const v=await request(action,{token});if(v.state!==(unsub?'unsubscribed':'subscribed'))throw Error('unavailable');result(unsub?'You’re unsubscribed.':'You’re on the list.',unsub?'You will not receive these email updates. Your coaching and app access are unchanged.':'Expect occasional notes, track photographs and confirmed run announcements from Brice. Every email has an unsubscribe link.','FORM email updates');token=null;}catch(e){$('token-status').textContent=errorText[e.message]||errorText.unavailable;if(e.message==='invalid_link')$('new-link').hidden=false;}finally{loading=false;$('token-button').disabled=false;}});
}else init();
})();
