-- W14 and W15: the block reaches the race.
--
-- Designed backward from race day rather than toward a taper number, so the
-- totals are what the structure produced: W14 lands near 36 against W13's 50,
-- and race week carries 24 before the race for José, 21 for Hope.
--
-- W14's Saturday keeps rhythm and asks nothing. W13's ten miles with four at
-- race pace was the last durability question and it was answered; there is
-- nothing useful left to prove seven days out.
--
-- Race week carries one touch of race pace, three by five minutes, deliberately
-- NOT eligible: we are touching the system, not testing ownership. Hope's
-- carries its own intent, because on 25 August she ran three of four reps under
-- her band and race week is where that costs the most.
--
-- The race IS eligible, and only its 13.1 component is. The warm-up is real
-- running and counts toward the week; it points at no mark. Eligibility is not
-- establishment — authoring the race as eligible awards nothing, and the filed
-- evidence still has to come back inside 6:30–6:45 to establish anything.
--
-- Everything before W14 is untouched.

do $$
declare
  jose_mark uuid := (select id from public.athlete_marks where athlete_id=(select id from public.athletes where slug='jose') and is_primary and active);
  hope_mark uuid := (select id from public.athlete_marks where athlete_id=(select id from public.athletes where slug='hope') and is_primary and active);
begin
  perform set_config('request.jwt.claims', '{"sub":"79d1520c-7c7c-4cd2-bd31-229a3cc56158"}', true);
  perform public.author_session((select id from public.athletes where slug='jose'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='jose') and week_number=14),'MON', 'Easy', 'Aerobic base. There is no floor — slower is never wrong.', date '2026-11-23', null, 7.0, 'mi', null, null, null,'[{"role": "work", "shape": "continuous", "position": 1, "distance": 7, "distanceUnit": "mi", "paceLowSeconds": 525}]'::jsonb, null);
  perform public.author_session((select id from public.athletes where slug='jose'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='jose') and week_number=14),'WED', 'Easy', 'Aerobic base. There is no floor — slower is never wrong.', date '2026-11-25', null, 6.0, 'mi', null, null, null,'[{"role": "work", "shape": "continuous", "position": 1, "distance": 6, "distanceUnit": "mi", "paceLowSeconds": 525}]'::jsonb, null);
  perform public.author_session((select id from public.athletes where slug='jose'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='jose') and week_number=14),'FRI', 'Easy', 'Aerobic base. There is no floor — slower is never wrong.', date '2026-11-27', null, 4.0, 'mi', null, null, null,'[{"role": "work", "shape": "continuous", "position": 1, "distance": 4, "distanceUnit": "mi", "paceLowSeconds": 525}]'::jsonb, null);
  perform public.author_session((select id from public.athletes where slug='jose'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='jose') and week_number=14),'SAT', 'Easy — long day, short', 'Rhythm, not a test. Last Saturday asked the durability question and it was answered.', date '2026-11-28', null, 8.0, 'mi', null, null, null,'[{"role": "work", "shape": "continuous", "position": 1, "distance": 8, "distanceUnit": "mi", "paceLowSeconds": 525}]'::jsonb, null);
  perform public.author_session((select id from public.athletes where slug='jose'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='jose') and week_number=15),'MON', 'Easy', 'Aerobic base. There is no floor — slower is never wrong.', date '2026-11-30', null, 6.0, 'mi', null, null, null,'[{"role": "work", "shape": "continuous", "position": 1, "distance": 6, "distanceUnit": "mi", "paceLowSeconds": 525}]'::jsonb, null);
  perform public.author_session((select id from public.athletes where slug='jose'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='jose') and week_number=15),'TUE', '3 × 5 min at race pace', 'One touch of race pace. Familiar, cheap, and finished wanting more.', date '2026-12-01', null, 5.85, 'mi', null, null, null,'[{"role": "warm_up", "shape": "continuous", "position": 1, "durationSeconds": 900}, {"role": "work", "shape": "repetitions", "position": 2, "durationSeconds": 300, "repeatCount": 3, "paceLowSeconds": 390, "paceHighSeconds": 405, "recoveryKind": "easy", "recoverySeconds": 180}, {"role": "cool_down", "shape": "continuous", "position": 3, "durationSeconds": 600}]'::jsonb, 'Under 6:30 is a different session.');
  perform public.author_session((select id from public.athletes where slug='jose'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='jose') and week_number=15),'WED', 'Easy', 'Aerobic base. There is no floor — slower is never wrong.', date '2026-12-02', null, 5.0, 'mi', null, null, null,'[{"role": "work", "shape": "continuous", "position": 1, "distance": 5, "distanceUnit": "mi", "paceLowSeconds": 525}]'::jsonb, null);
  perform public.author_session((select id from public.athletes where slug='jose'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='jose') and week_number=15),'THU', 'Easy with strides', 'A little mechanical brightness. Relaxed, not fast.', date '2026-12-03', null, 4.5, 'mi', null, null, null,'[{"role": "work", "shape": "continuous", "position": 1, "distance": 4, "distanceUnit": "mi", "paceLowSeconds": 525}, {"role": "work", "shape": "repetitions", "position": 2, "durationSeconds": 20, "repeatCount": 4, "recoveryKind": "easy", "recoverySeconds": 60}]'::jsonb, null);
  perform public.author_session((select id from public.athletes where slug='jose'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='jose') and week_number=15),'FRI', 'Easy — shakeout', 'Short and unhurried. Nothing to gain today, something to lose.', date '2026-12-04', null, 3.0, 'mi', null, null, null,'[{"role": "work", "shape": "continuous", "position": 1, "distance": 3, "distanceUnit": "mi", "paceLowSeconds": 525}]'::jsonb, null);
  perform public.author_session((select id from public.athletes where slug='jose'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='jose') and week_number=15),'SAT', 'OUC Half', 'Thirteen point one, continuous, at the pace this whole block has been learning to carry.', date '2026-12-05', null, 14.81, 'mi', null, null, null,replace('[{"role": "warm_up", "shape": "continuous", "position": 1, "durationSeconds": 900}, {"role": "work", "shape": "continuous", "position": 2, "distance": 13.1, "distanceUnit": "mi", "paceLowSeconds": 390, "paceHighSeconds": 405, "countsTowardMarkId": "__JOSE__"}]', '__JOSE__', jose_mark::text)::jsonb, null);
  perform public.author_session((select id from public.athletes where slug='hope'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='hope') and week_number=14),'MON', 'Easy', 'Aerobic base. There is no floor — slower is never wrong.', date '2026-11-23', null, 7.0, 'mi', null, null, null,'[{"role": "work", "shape": "continuous", "position": 1, "distance": 7, "distanceUnit": "mi", "paceLowSeconds": 525}]'::jsonb, null);
  perform public.author_session((select id from public.athletes where slug='hope'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='hope') and week_number=14),'WED', 'Easy', 'Aerobic base. There is no floor — slower is never wrong.', date '2026-11-25', null, 6.0, 'mi', null, null, null,'[{"role": "work", "shape": "continuous", "position": 1, "distance": 6, "distanceUnit": "mi", "paceLowSeconds": 525}]'::jsonb, null);
  perform public.author_session((select id from public.athletes where slug='hope'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='hope') and week_number=14),'FRI', 'Easy', 'Aerobic base. There is no floor — slower is never wrong.', date '2026-11-27', null, 4.0, 'mi', null, null, null,'[{"role": "work", "shape": "continuous", "position": 1, "distance": 4, "distanceUnit": "mi", "paceLowSeconds": 525}]'::jsonb, null);
  perform public.author_session((select id from public.athletes where slug='hope'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='hope') and week_number=14),'SAT', 'Easy — long day, short', 'Rhythm, not a test. Last Saturday asked the durability question and it was answered.', date '2026-11-28', null, 8.0, 'mi', null, null, null,'[{"role": "work", "shape": "continuous", "position": 1, "distance": 8, "distanceUnit": "mi", "paceLowSeconds": 525}]'::jsonb, null);
  perform public.author_session((select id from public.athletes where slug='hope'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='hope') and week_number=15),'MON', 'Easy', 'Aerobic base. There is no floor — slower is never wrong.', date '2026-11-30', null, 6.0, 'mi', null, null, null,'[{"role": "work", "shape": "continuous", "position": 1, "distance": 6, "distanceUnit": "mi", "paceLowSeconds": 525}]'::jsonb, null);
  perform public.author_session((select id from public.athletes where slug='hope'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='hope') and week_number=15),'TUE', '3 × 5 min at race pace', 'Settle at 6:45. Do not chase faster. Finish wanting another rep.', date '2026-12-01', null, 5.85, 'mi', null, null, null,'[{"role": "warm_up", "shape": "continuous", "position": 1, "durationSeconds": 900}, {"role": "work", "shape": "repetitions", "position": 2, "durationSeconds": 300, "repeatCount": 3, "paceLowSeconds": 390, "paceHighSeconds": 405, "recoveryKind": "easy", "recoverySeconds": 180}, {"role": "cool_down", "shape": "continuous", "position": 3, "durationSeconds": 600}]'::jsonb, 'Under 6:30 is a different session.');
  perform public.author_session((select id from public.athletes where slug='hope'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='hope') and week_number=15),'WED', 'Easy', 'Aerobic base. There is no floor — slower is never wrong.', date '2026-12-02', null, 5.0, 'mi', null, null, null,'[{"role": "work", "shape": "continuous", "position": 1, "distance": 5, "distanceUnit": "mi", "paceLowSeconds": 525}]'::jsonb, null);
  perform public.author_session((select id from public.athletes where slug='hope'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='hope') and week_number=15),'THU', 'Easy with strides', 'A little mechanical brightness. Relaxed, not fast.', date '2026-12-03', null, 4.5, 'mi', null, null, null,'[{"role": "work", "shape": "continuous", "position": 1, "distance": 4, "distanceUnit": "mi", "paceLowSeconds": 525}, {"role": "work", "shape": "repetitions", "position": 2, "durationSeconds": 20, "repeatCount": 4, "recoveryKind": "easy", "recoverySeconds": 60}]'::jsonb, null);
  perform public.author_session((select id from public.athletes where slug='hope'),(select id from public.training_weeks where athlete_id=(select id from public.athletes where slug='hope') and week_number=15),'SAT', 'OUC Half', 'Thirteen point one, continuous, at the pace this whole block has been learning to carry.', date '2026-12-05', null, 14.81, 'mi', null, null, null,replace('[{"role": "warm_up", "shape": "continuous", "position": 1, "durationSeconds": 900}, {"role": "work", "shape": "continuous", "position": 2, "distance": 13.1, "distanceUnit": "mi", "paceLowSeconds": 390, "paceHighSeconds": 405, "countsTowardMarkId": "__HOPE__"}]', '__HOPE__', hope_mark::text)::jsonb, null);
  -- The last session still declaring its work as its whole self. Its warm-up
  -- and cool-down were typed from the start and never counted; eligibility is
  -- restated on the wire so the revision cannot drop it.
  perform public.revise_session((select s.id from public.planned_sessions s join public.athletes a on a.id=s.athlete_id where a.slug='jose' and s.scheduled_on = date '2026-11-24' limit 1),
    '4 mi at race pace', null,
    'prescribed_distance is the whole session, not the work inside it. The fifteen-minute warm-up and ten-minute cool-down were always run and were never counted. No hard piece changes.',
    6.86, 'mi', null, null, null, replace('[{"role":"warm_up","shape":"continuous","position":1,"durationSeconds":900},{"role":"work","shape":"continuous","position":2,"distance":4,"distanceUnit":"mi","paceLowSeconds":390,"paceHighSeconds":405,"countsTowardMarkId":"__JOSE__"},{"role":"cool_down","shape":"continuous","position":3,"durationSeconds":600}]', '__JOSE__', jose_mark::text)::jsonb, null);
  -- The last session still declaring its work as its whole self. Its warm-up
  -- and cool-down were typed from the start and never counted; eligibility is
  -- restated on the wire so the revision cannot drop it.
  perform public.revise_session((select s.id from public.planned_sessions s join public.athletes a on a.id=s.athlete_id where a.slug='hope' and s.scheduled_on = date '2026-11-24' limit 1),
    '4 mi at race pace', null,
    'prescribed_distance is the whole session, not the work inside it. The fifteen-minute warm-up and ten-minute cool-down were always run and were never counted. No hard piece changes.',
    6.86, 'mi', null, null, null, replace('[{"role":"warm_up","shape":"continuous","position":1,"durationSeconds":900},{"role":"work","shape":"continuous","position":2,"distance":4,"distanceUnit":"mi","paceLowSeconds":390,"paceHighSeconds":405,"countsTowardMarkId":"__HOPE__"},{"role":"cool_down","shape":"continuous","position":3,"durationSeconds":600}]', '__HOPE__', hope_mark::text)::jsonb, null);
end $$;
